### ISSUE TITLE
License unclear for logos

### ISSUE THREAD

**Issue by penyuan** [nasa/Transform-to-Open-Science#103]
I randomly noticed this line in [this page about the logos](https://github.com/nasa/Transform-to-Open-Science/tree/main/assets/logos): 

`CCA 4.0`

Do you mean the [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/) license? If so, it should be `CC BY 4.0` instead. I'd be happy to submit a pull request with the change if that helps.

**Comment by libcce** [comment]
Thanks @penyuan put in a PR for this fix https://github.com/nasa/Transform-to-Open-Science/pull/104. Zenodo used this license so I figured it was the license you mentioned above.
