### ISSUE TITLE
Stay in sync with UNESCO open science implementation working group

### ISSUE THREAD

**Issue by penyuan** [nasa/Transform-to-Open-Science#118]
(don't know if this should be an issue or go in [Discussions](https://github.com/nasa/Transform-to-Open-Science/discussions), please correct me)

As many of you know, the [UNESCO Recommendation on Open Science](https://en.unesco.org/science-sustainable-future/open-science/recommendation) was ratified in November 2021, and there is now an [implementation group](https://www.unesco.org/en/natural-sciences/open-science/implementation).

They have a [Working Group on Open Science Infrastructures](https://events.unesco.org/event?id=1410269731&lang=1033) which "will be developing a series of supporting tools - technical briefs, fact sheets, guidelines and **training materials** - that will constitute an online ‘living’ Open Science Toolkit" (emphasise mine) and have their [first meeting](https://events.unesco.org/event?id=1410269731&lang=1033) on 7th July 2022.

I am flagging this meeting so that the NASA TOPS folks can stay in sync with this important effort and avoid re-inventing any wheels!

**Comment by cgentemann** [comment]
Pen - Thanks so much. The UNESCO recommendations were the initial guide TOPS used to develop the 4 areas of action. We are attending all their meetings - but I don't think this one was on our radar so thanks so much for pointing it out. @reeseIngraham can we please add this to our TOPS calendar of events? Also tagging @Earth2Ivey.
