### ISSUE TITLE
Add description of material for website

### ISSUE THREAD

**Issue by nasacrawford** [nasa/Transform-to-Open-Science#16]
Add a draft of the documentation that we would want added to the website in the future.

**Comment by cgentemann** [comment]
@kablukiw @emilyscassidy Do you have an outline of what material we still need to generate or do you have most of what you need on the TOPS gdrive?

**Comment by emilyscassidy** [comment]
> @kablukiw @emilyscassidy Do you have an outline of what material we still need to generate or do you have most of what you need on the TOPS gdrive?

Added some draft text to a Google doc here: https://docs.google.com/document/d/1Wo3XJ91jKBgAhnh0i6ODwSdPH5QUgKm1h-Vx-UDoHP0/edit?usp=sharing
