### ISSUE TITLE
Set up for deploying the Website for TOPS from GitHub

### ISSUE THREAD

**Issue by nasacrawford** [nasa/Transform-to-Open-Science#2]
We will want to develop a website to host information about Transform to Open Science and the Year of Open Science 2023. 

- [ ] Submit NTRS
- [ ] Determine technology to use for hosting a website
- [ ] Determine best way to host the website
- [ ] Submit SRA
- [ ] Setup infrastructure for the webpages
- [ ] Deploy first page

**Comment by cgentemann** [comment]
Could we just host the website at Transform-to-Open-Science.github.io and use a Jekyll theme that auto-builds? eg. https://mmistakes.github.io/minimal-mistakes/. Would this make the SRA easier?

**Comment by nasacrawford** [comment]
Great suggestion -- I think @steadyflux and I are  going to take a look into a couple of different options, but I think listing a few different options as part of this issue would be helpful.

**Comment by axi0m** [comment]
I am unsure if I can assist here in anyway BUT, I do have a bit of experience with Hugo and GitHub Actions and Netlify to deploy a website after git push. Leveraging GitHub IO and Jekyll theme will probably have the least friction/overhead overall.

**Comment by JonanOribe** [comment]
Netlify or Railway could be good options. I have some questions about this.

- [ ] The web site will have graphs or animations?
- [ ] We are looking for a web with fixed content or something more complex(searching bar, components, maps,etc )? On the second option we must create  an API to manage the connection against the database, but the first one could simply be a Wordpress.
- [ ] All the website will be open or some areas should require login?

About technology, with a framework like Vue or React, it's easy to deploy something fast and with a nice look. I have been working lately with the guys from NASA Open MCT (https://nasa.github.io/openmct/about-open-mct/) and everything runs over Vue.

Thinking on the design, we can use https://penpot.app/ for the look and feel.

**Comment by bello-mart-isabella** [comment]
@paigem This seems related to what you have been doing lately

**Comment by bressler95tops** [comment]
Closing this older issue out since our deployment method for GitHub pages is what we ran with for a while, and we will be depending more on nasa.gov due to web modernization.
