### ISSUE TITLE
Create Discuss Forum to foster community discussions and knowledge sharing

### ISSUE THREAD

**Issue by cgentemann** [nasa/Transform-to-Open-Science#20]
Can we set up discussions on the github site? I just asked in the pangeo gitter & got a lot of good comments --- 
Seems like it is useful to have both discourse for more accessible discussion and use github as well with a link to discourse.
https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/enabling-or-disabling-github-discussions-for-a-repository
It seems like you configure it for a single repro through a config file:
https://github.com/scikit-hep/awkward-1.0/blob/main/.github/ISSUE_TEMPLATE/config.yml

**Comment by nasacrawford** [comment]
@JustinGOSSES is it possible to enable a discussion board on here?

**Comment by JustinGOSSES** [comment]
https://github.com/nasa/Transform-to-Open-Science/discussions/22   Done

**Comment by JustinGOSSES** [comment]
https://github.com/nasa/Transform-to-Open-Science/discussions/
