### ISSUE TITLE
🔒 - Create a SECURITY.md file and reference the NASA VDP

### ISSUE THREAD

**Issue by axi0m** [nasa/Transform-to-Open-Science#253]
Template for [SECURITY.md](https://github.com/microsoft/repo-templates/blob/main/shared/SECURITY.md)

Reference to add:`https://www.nasa.gov/vulnerability-disclosure-policy`

**Comment by abhilipsasahoo03** [comment]
Hello, can I work on this?

**Comment by axi0m** [comment]
I think that is great however @Earth2Ivey will need to actually assign it to you since she has write access to the repository. Make sure you're following the NASA Org https://github.com/nasa. 

![image](https://user-images.githubusercontent.com/2532857/191016102-4f48f21c-9591-4d8d-8d72-e8c50ed8fea1.png)

**Comment by abhilipsasahoo03** [comment]
> I think that is great however @Earth2Ivey will need to actually assign it to you since she has write access to the repository. Make sure you're following the NASA Org https://github.com/nasa. 
> 
> ![image](https://user-images.githubusercontent.com/2532857/191016102-4f48f21c-9591-4d8d-8d72-e8c50ed8fea1.png)
> 

So I think I should wait a little longer before I start working on this to avoid duplication of efforts or anything. Waiting to get assigned. :)

**Comment by abhilipsasahoo03** [comment]
@axi0m i think we can close this issue now?
