### ISSUE TITLE
Add link to the deployed GitHub site on the repo

### ISSUE THREAD

**Issue by logankilpatrick** [nasa/Transform-to-Open-Science#276]
Under the repo settings, there's a link now that the repo is deployed as a site, can we add that to the description of the repo?

**Comment by cgentemann** [comment]
we are still waiting on permissions to deploy as a site.

**Comment by cgentemann** [comment]
done! still working to update links & look of jupyter book, but it is live and I added a link to the readme.md.

https://github.com/nasa/Transform-to-Open-Science/commit/cb1bddafc113e46a24c7457ec5ba869b84a1b572
