### ISSUE TITLE
Add contribution section to highlight people who contribute to this REPO

### ISSUE THREAD

**Issue by logankilpatrick** [nasa/Transform-to-Open-Science#299]
I was chatting with @bello-mart-isabella about making sure we showcase the work folks are doing in this repo and beyond. One thing discussed was using a bot like: https://allcontributors.org/docs/en/bot/overview to highlight people in the README who have contributed. 

One thing in particular that I like about this is that it is not bound to those who have committed to this repo specifically. If someone made a valuable contribution in a community forum call, we could use the bot to do this. One other option is to have a GitHub Action where we look at all contributions made to the repo and highlight them here. That would not be very different from the existing approach GitHub uses to show contributors on the right side of the repo. 

I can try and look around to see if there's other tools out there but the one suggested by @bello-mart-isabella looks awesome!

**Comment by bello-mart-isabella** [comment]
@logankilpatrick You may have noticed that we implemented this suggestion!! We now even have the bot configured so that it updates both our repo README and the TOC file which we use for our JupyterBook. Thank you for talking through these ideas with me two months back
