### ISSUE TITLE
Restructure the "Get started" chapter of the JupyterBook

### ISSUE THREAD

**Issue by paigem** [nasa/Transform-to-Open-Science#319]
The information under "Get Started" is currently not well organized and repetitive. This needs a revamp: pages need to be consolidated and the table of contents likely needs to be updated.

**Comment by bello-mart-isabella** [comment]
Completed!

**Comment by PaigeDAO** [comment]
Is anyone attending Jupytercon in Paris in May?  https://www.jupytercon.com/about  (I am - would welcome connecting)
