### ISSUE TITLE
book-requirements.txt should contain dependencies version

### ISSUE THREAD

**Issue by JonanOribe** [nasa/Transform-to-Open-Science#323]
At this moment, the requirements from the book are only set with the dependencies names, but this could bring problems because even if at this moment something works does not mean that in 3 months everything will run with no problem. 

![image](https://user-images.githubusercontent.com/11914201/201545679-94834912-6c94-47e6-a827-32f8c0347800.png)

This is because **pip install** downloads the last version of the libraries at install time, so if now we are working with pandas 1.0.25 but in 3 months someone tries to run book-requirements.txt and automatically downloads 1.1.27 maybe some incompatibilities will appear and noone will remember what the exact versions were for each dependency.

It will be a good idea to set the version of the libaries in the document, like **jupyter-book==0.13.1** instead of simply **jupyter-book**

**Comment by paigem** [comment]
Thanks @JonanOribe - this is a good suggestion. I assume then that we will periodically want to update the pinned version once we have tested the book with the new library versions?

**Comment by JonanOribe** [comment]
Ya, that's the idea, to have a latest stable version to be sure that everyones is working with the same "source of true".We can review the dependecies evey quarter to update libraries and after test the new version, if everything runs it is time for update the repository's version, if not, rollback. I created a pull request for solve this issue [https://github.com/nasa/Transform-to-Open-Science/pull/325](url)
