### ISSUE TITLE
Collaboration section for research and publications

### ISSUE THREAD

**Issue by JonanOribe** [nasa/Transform-to-Open-Science#334]
I have a proposal to make and I hope to be able to explain it in a simple way.

I am a software engineer who has spent years in private companies working on cloud technologies and data science. I have always liked science a lot, but my profile is very technical. On the other hand, I have seen many scientists with great skills, but difficulties when it comes to programming their simulations, Jupyter Books or working with a database.

Personally, I would consider it a great contribution to open science to have a place (something like a forum) where technical profiles, citizens and scientists could collaborate in the development of experiments and papers.

I mean, if, for example, a physicist or a biologist needs help preparing their next paper, they can appeal to the community looking for someone with skills to work on Jupyter, Python, collecting information from different databases or whatever necessary and collaborate together.

It would be a way to streamline posts, present them more clearly (cleaner and easier to understand code, better graphics, automatic tests that check each change in the code to ensure that everything is still in order, etc.) and at the same time, many people without scientific profile could collaborate contributing with their capacities.

**Comment by PaigeDAO** [comment]
In support of something along these lines that you propose @JonanOribe here, we have developed #FrontierRegistry . Researchers are able to easily publish (register) their work on-chain prior to making their work available for collaboration amongst their peers.
