### ISSUE TITLE
updating links on Year of Open Science website

### ISSUE THREAD

**Issue by amandalbradford** [nasa/Transform-to-Open-Science#371]
Aloha - I work at NOAA Fisheries, where we have definitely been following along with TOPS, including the declaration of 2023 as the Year of Open Science! I was sharing the [Year of Open Science website](https://nasa.github.io/Transform-to-Open-Science/year-of-open-science/) with some of my leadership and noticed all four of the Guide links on that page throw an error. They work fine through the ReadMe, so it seems they just need to be updated on the website, and I wanted to let you all know. Thanks for leading the charge with TOPS!

All best,
amanda

**Comment by lisa-gethard** [comment]
Hello. I am a NASA/JPL Solar System Ambassador, NASA Citizen Scientist with The GLOBE Program and have been following the activitiy with TOPS, Year of Open Science, Open Source 2023. I am looking forward to the announcements this week and will be holding presentation Saturday, January 14, 2023 for public outreach, community engagement with Year of Open Science.  Thank you for all your support!

**Comment by amandalbradford** [comment]
Thank you!
