### ISSUE TITLE
Add presentation slides summarizing SPD-41a for scientists funded by SMD

### ISSUE THREAD

**Issue by itsmoosh** [nasa/Transform-to-Open-Science#421]
I gave a presentation to a JPL audience (mainly scientists) summarizing SPD-41a. The slides have been cleared through the JPL release process, and I think they would be useful to many others. I intend to a link under a related announcement in the README.

**Comment by bressler95tops** [comment]
I can see this issue was addressed in PR #422, feel free to reopen if there is any other action to take on this.
