### ISSUE TITLE
Where data producer scientists should put open software used to produce products

### ISSUE THREAD

**Issue by deborahUAH** [nasa/Transform-to-Open-Science#45]
I deal quite often now with questions from Earth Venture Suborbital science teams (there are 5 current EVS-3 projects) and these teams have a requirement to deliver their data product software and code by the completion of the project and need to know where to deliver to.  Currently the answer is to check with the DAAC, but the DAACs are currently not ready to do this (different levels of readiness, from "we don't do that" to "we have a DAAC github, lets put it there").  Coordination and uniform communication about what the teams are to do is very needed, and quickly.  Happy to discuss more.

**Comment by cgentemann** [comment]
@nasacrawford it seems like uploading to project github site, apply open permissive licenses, creating DOI with zenodo, including DOI in ATBD, then reporting this to the DAAC for inclusion in the EVS data landing page would satisfy all requirements? This way each data product could get their own DOI for each ATBD.  We could put this in the FAQ: Ask them to do above & for help follow https://guides.lib.berkeley.edu/citeyourcode.

**Comment by nasacrawford** [comment]
We will be providing further guidance on it (see the [information policy website](https://science.nasa.gov/researchers/science-data/science-information-policy)) , and I'll have to check with @steadyflux for ESD policy, but these is what I would recommend right now:

- If they are at a NASA Center or JPL, they should follow the software release process and contact their software release authority representative.  They can find more information at [code.nase.gov](https://code.nasa.gov).
 
- If they not at a NASA Center or JPL, we do not have specific general guidance for this at this time, but the important aspect is their code should be open source.  The process @cgentemann describes is similar to what I would recommend:
1.   Make the code available on a version control platform like GitHub
2.  When releasing the code, create a DOI for the release. For example, if using GitHub, this can be [done automatically with Zenodo](https://guides.github.com/activities/citable-code/)
3.  Make it clear in the r[epository how to cite the code](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)
4. Also considering adding a meta file describing your software.
5. There is also the aspect of reporting the technology and we will be providing more guidance on that.
