### ISSUE TITLE
Consider redefining the TOPS acronym

### ISSUE THREAD

**Issue by Daniel-Mietchen** [nasa/Transform-to-Open-Science#54]
I think the current acronym definition ```Transform to OPen Science (TOPS)``` could be improved by having the ```P``` stand for ```participatory```: ```Transform to Open and Participatory Science (TOPS)```.

Yes, a good part of open science projects is already actively or passively facilitating participation by people not formally involved, but some parts of the open science landscape (e.g. initiatives that share their workflows only retroactively, e.g. after some key publication is out), actively or passively exclude such broader participation.

Conversely, many participatory science projects (usually framed in terms of citizen science) are only partially open, with much of their research workflows (especially study design and publications) not open to participation. 

Having a prominent initiative like TOPS stress that it is desirable for open science projects to be more participatory and for participatory science projects to be more open would be a strong signal to both communities to pay more attention to interactions between open science and participatory science.

**Comment by cgentemann** [comment]
Thanks for the suggestion, this is something we will think about.
