### ISSUE TITLE
Curriculum Schedule

### ISSUE THREAD

**Issue by cgentemann** [nasa/Transform-to-Open-Science#540]
@bressler95tops 
can you please add the curriculum development schedule to https://github.com/nasa/Transform-to-Open-Science/blob/main/docs/Area2_Capacity_Sharing/Open-Science-101/curriculum_leads.md?

@pmbremner has current schedule. 
Thanks!

**Comment by bressler95tops** [comment]
thank you @cgentemann I will get in contact with @pmbremner  to confirm that information

**Comment by bressler95tops** [comment]
Reached out to Paul and he mentioned he need to have a conversation tomorrow so we can have solid details about the development schedules, I will keep in touch with him to make sure this gets done.

**Comment by bressler95tops** [comment]
Addressed in PR #543 and subsequent revisions with Paul's help.  I will leave this open for a little bit in case there is anything missing.

**Comment by bressler95tops** [comment]
It would seem that announcements were added but then removed in favor of this updated format before launch @cgentemann, I can close this out unless you believe something like this should still be added
