### ISSUE TITLE
Create a open science event calendar

### ISSUE THREAD

**Issue by cgentemann** [nasa/Transform-to-Open-Science#55]

**Comment by micahvandegrift** [comment]
One exists! https://openresearchcalendar.org/

**Comment by chall-nasa** [comment]
Thank you [micahvandegrift](https://github.com/micahvandegrift) for sharing this calendar.

**Comment by libcce** [comment]
@nasacrawford set up a discussion https://github.com/nasa/Transform-to-Open-Science/discussions/27 calendar has come up there too.

**Comment by cgentemann** [comment]
@chall-nasa maybe add monthly forum to [https://openresearchcalendar.org/calendar/](https://openresearchcalendar.org/calendar/)?
