### ISSUE TITLE
Citing OS101 materials: Incorrect DOI

### ISSUE THREAD

**Issue by shilaan** [nasa/Transform-to-Open-Science#580]
The DOI for citing OS101 materials appears to be incorrect. 

<https://openscience101.org/contributor> and <https://github.com/nasa/Transform-to-Open-Science/blob/edcd2f4e49f1e449ca57285225d08eb4922c7e99/docs/Area2_Capacity_Sharing/Open-Science-101/curriculum_leads.md> both mention the following DOI: 10.5281/zenodo.10161527. 

However, this DOI does not exist, see:
<https://zenodo.org/doi/10.5281/zenodo.10161527>
<https://zenodo.org/records/10161527>

Both links lead to a "Page not found" error. Could the DOI be updated, so we can properly cite the OS101 materials?

**Comment by bressler95tops** [comment]
@shilaan we appreciate the patience, after much internal discussions we have released the DOI for the OS101 curriculum and the links you mentioned should be resolving now.  More information is mentioned in the [v1.0.0 release.](https://github.com/nasa/Transform-to-Open-Science/releases/tag/v1.0.0)
