### ISSUE TITLE
OS101_M1/Lesson 2 - Minor Typo

### ISSUE THREAD

**Issue by g-r-a-e-m-e** [nasa/Transform-to-Open-Science#582]
Hello! I hope you're all well. I noticed what might be a minor typo in
`Module 1: The Ethos of Open Science/Lesson 2: Why is Open Science Important?`

Should the text outlined in red be "Participants" or is it correct as is?

<img width="1205" alt="os101-m1-l2-typo-2023-12-10" src="https://github.com/nasa/Transform-to-Open-Science/assets/62527977/6b862002-dd13-44b7-8d27-8714e16b2d46">

Thank you!

**Comment by bressler95tops** [comment]
Thanks for the suggestion @g-r-a-e-m-e this change makes sense to me, I will flag this issue to be taken care of, the location for our purposes on the development version of the curriculum is here: https://github.com/nasa/Transform-to-Open-Science/tree/main/docs/Area2_Capacity_Sharing/Open-Science-101/modules/Module_1/Lesson_2

**Comment by katblanchette** [comment]
@bressler95tops - Please correct.

**Comment by bressler95tops** [comment]
Thank you @katblanchette I have addressed the issue in M1L2, for your reference (and for the MOOC developers) you may look at PR #748 to see the exact change.  The exact text change is [under the files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/748/files) of the referenced Pull Request. Let me know when you are able to get that updated on the MOOC.

**Comment by katblanchette** [comment]
Thank you @bressler95tops for the update. I have submitted the update for the MOOC and will notify you when it is complete.

**Comment by bressler95tops** [comment]
Added PR #752 to add the sentence you mentioned @katblanchette.  MOOC developers can check the ['files changed'](https://github.com/nasa/Transform-to-Open-Science/pull/752/files) tab same as the first PR.

**Comment by bressler95tops** [comment]
Thank you for you patience @katblanchette @g-r-a-e-m-e the change has been made on both the MOOC and GitHub.
