### ISSUE TITLE
OS101 Module 2 - Lesson 4 - Errors

### ISSUE THREAD

**Issue by xuanxu** [nasa/Transform-to-Open-Science#586]
Here's a couple of errors I noticed in the OS101 Module 2:

### Module 2 / Lesson 4 / Quiz

The quiz at the end of the lesson 4 includes the following question:
`A software repository and a software archive are the same thing` 

The correct anwser is `False`, but the quiz expect `True` as the correct one.

In the final assesment test of the module, the question appears again and this time it expects correctly `False`

### Module 2 / Lesson 4 /  Section: Tools for Editing Code

This is probably something to be fixed at [ProjectPythia/pythia-foundations ](https://github.com/ProjectPythia/pythia-foundations) but the 4th activity, Tools for Editing Code, points to an [example](https://hub.projectpythia.org/user/projectpythia-pythia-foundations-ukbzama3/lab/tree/core/xarray/enso-xarray.ipynb) Jupiter notebook. Following the provided instructions, the code does not run, it fails in the import section: 

![binder_error](https://github.com/nasa/Transform-to-Open-Science/assets/6528/31292757-8315-4c64-96e7-0399882a4825)

**Comment by bressler95tops** [comment]
Thanks @xuanxu I will elevate this issue to the curriculum team

**Comment by bressler95tops** [comment]
After further investigation, it seems that the pkgutil.ImpImporter class may actually be deprecated in Python 3.12 and may need some additional work arounds to get it to work with this example.  I will raise an issue at the repository mentioned.

**Comment by bressler95tops** [comment]
The developers were quick to follow up @xuanxu it does seem that [a solution](https://github.com/ProjectPythia/pythia-foundations/issues/441) was implemented a short while ago and I can see that you are using BinderHub as the example in the curriculum guides you to do.  They seem to have updated some dependencies that were not updated for a long time predating newer python versions. I ran the import cell in BinderHub and it looks to not cause any errors but let myself or the folks at ProjectPythia know if you are still having an issue with it.

**Comment by katblanchette** [comment]
@bressler95tops - Do you need our OS101 team to disposition this comment?

**Comment by katblanchette** [comment]
@bressler95tops - Thank you for the clarification and for updating the content. I double checked the knowledge check question in the ILT slides and in the MOOC, and both list "False" as the correct answer. After the update is facilitated in the GitHub, this issue may be closed.

**Comment by bressler95tops** [comment]
Sounds good @katblanchette we should be good then since the knowledge checks on GitHub do not highlight the correct answer, and we don't have module assessments since that was our collective decision at the time. I can mark this as complete since it should be good to go on the MOOC side of things, I also gave the quiz a test on my end.
