### ISSUE TITLE
OS101 Module 2 Lesson 1 - Libraries definition error

### ISSUE THREAD

**Issue by Catch2T8** [nasa/Transform-to-Open-Science#588]
In [Lesson ](https://github.com/nasa/Transform-to-Open-Science/tree/open-science-101/Module_2/Lesson_1)1 of Module 2 of Open Science 101 course, "Libraries" defined as:

> No creative process is truly complete until it manifests a tangible reality. Whether your idea is an action or a physical creation, bringing it to life will likely involve the hard work of iteration, testing, and refinement.
> 
> Just be wary of perfectionism. Push yourself to share your creations with others. By maintaining an open stance, you’ll be able to learn from their feedback. Consider their responses new material that you can draw from the next time you’re embarking on a creative endeavor.

![Screenshot 2023-12-13 202439](https://github.com/nasa/Transform-to-Open-Science/assets/6470808/87d530c7-0833-49a3-98dc-46b5ed3a58fb)

I don't think this is a good description for libraries used for software development. Is there a way to check and look into this learning material? Thanks.

**Comment by nasacrawford** [comment]
Thanks for the feedback - that does seem like something is amiss there.   

Libraries should have the following definition: 

> Generic tools that implement well-known algorithms, provide statistical analysis or visualization, etc., which are incorporated in other software categories.

It will need to be updated in this file: https://github.com/nasa/Transform-to-Open-Science/tree/main/docs/Area2_Capacity_Sharing/Open-Science-101/modules/Module_2/Lesson_1

**Comment by bressler95tops** [comment]
Thanks @Catch2T8 for the contribution.  And thank you @nasacrawford for the revised definition, this definitely makes more sense as a definition for this coming from the software world myself.  I will compile these recent corrections to get it over to the curriculum team.

**Comment by danielskatz** [comment]
This new definition appears to be in the on-line version, so I think this issue can be closed as resolved now

**Comment by katblanchette** [comment]
@bressler95tops - Double checking - is this issue closed? Thanks!

**Comment by katblanchette** [comment]
@bressler95tops - i am not finding the definition of Libraires in the Key Terms under M2 L1. Is this still an active issue? Thanks!

**Comment by katblanchette** [comment]
@bressler95tops - Please change "Libraries" definition to "Generic tools that implement well-known algorithms, provide statistical analysis or visualization, etc., which are incorporated in other software categories." Thank you!

**Comment by bressler95tops** [comment]
Thank you @katblanchette I have addressed the issue in M2L1. For your reference (and for the MOOC developers) you may look at PR #801 to see the exact change. The exact text change is [under the files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/801/files) of the referenced Pull Request. Let me know when you are able to get that updated on the MOOC.

We appreciate your patience on this @Catch2T8

**Comment by Catch2T8** [comment]
Saw the updated definition of `Libraries`  at Module 2 Lesson 1

> Generic tools that implement well-known algorithms, provide statistical analysis or visualization, etc., which are incorporated in other software categories.

![2024-08-03](https://github.com/user-attachments/assets/c1127e00-7a4f-410a-b277-9d2fcdaa666a)

Appreciate in hearing my concern and keep up the good work.

**Comment by bressler95tops** [comment]
Thank you for your patience @Catch2T8 we are closing out this issue as resolved.
