### ISSUE TITLE
OS101 Module 2 Lesson 1 - People You Know weird text

### ISSUE THREAD

**Issue by Catch2T8** [nasa/Transform-to-Open-Science#598]
In [Lesson 2](https://github.com/nasa/Transform-to-Open-Science/tree/main/docs/Area2_Capacity_Sharing/Open-Science-101/modules/Module_3/Lesson_2) of Module 3 of Open Science 101 course, there's a weird text in the **People You Know (Online or In-person!)** section:

> When we show up to the present moment with all of our senses, we invite the world to fill us with joy. The pains of the past are behind us. The future has yet to unfold. But the now is full of beauty simply waiting for our attention.

![Screenshot 2023-12-31 180013](https://github.com/nasa/Transform-to-Open-Science/assets/6470808/efac063a-acb8-41c4-a5f8-afc42b267dc6)

I don't think the above-mentioned text brings context in discovering open data.

Appreciate to take a glimpse and review this section.

**Comment by bressler95tops** [comment]
Thank you @Catch2T8 it appears that someone has brought this to attention in PR #600 for that specific paragraph, this will get addressed in that PR
