### ISSUE TITLE
OS101 Module 3 Lesson 1 - Check weird text.

### ISSUE THREAD

**Issue by TomLav** [nasa/Transform-to-Open-Science#599]
The 2nd sentence in this [line](https://github.com/nasa/Transform-to-Open-Science/blob/b9caecbe0846929836c8ecb379b9ecb4a6a61aa2/docs/Area2_Capacity_Sharing/Open-Science-101/modules/Module_3/Lesson_1/readme.md?plain=1#L223) is hard to understand and should probably be reworded.

> FAIR principles help researchers make better use of, and engage with a broader audience with, their scientific data than outdated techniques would allow.

Possibly:

> FAIR principles help researchers make better use of their scientific data, and engage with a broader audience, than outdated techniques would allow.

**Comment by bressler95tops** [comment]
Thanks @TomLav I agree with this revision of this text and will see what some of our people at the project office think.

**Comment by bressler95tops** [comment]
Changed title to Lesson 1 after checking the referenced line

**Comment by katblanchette** [comment]
@bressler95tops  - Please correct.

**Comment by bressler95tops** [comment]
Thank you @katblanchette I have addressed the issue in M3L1. For your reference (and for the MOOC developers) you may look at PR #749 to see the exact change. The exact text change is under the [files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/749/files) of the referenced Pull Request. Let me know when you are able to get that updated on the MOOC.

**Comment by katblanchette** [comment]
Thank you @bressler95tops. The OS101 Team has also updated the sentence in the Instructor Lead Training deck and submitted the update to the MOOC. We will notify you when the MOOC update is complete.

**Comment by bressler95tops** [comment]
Thank you @katblanchette and @TomLav this issue has been addressed and I will be closing it out.  We are always happy to accept more feedback if you have any.
