### ISSUE TITLE
OS101 Module 3 Lesson 1 - Typo

### ISSUE THREAD

**Issue by brian-knosp** [nasa/Transform-to-Open-Science#601]
"critical" is misspelled in the Overview in Lesson 1:

In addition, the lesson takes a closer look at how FAIR applies to open data as well as at the **criticall** role of metadata.

**Comment by bressler95tops** [comment]
Thank you Brian, we will review this, but it sounds like something that does need to be fixed, I will be addressing the issue and communicating this with the curriculum team as well.

**Comment by katblanchette** [comment]
@bressler95tops - Please correct.

**Comment by bressler95tops** [comment]
@brian-knosp @katblanchette thank you for your patience on this.  I can confirm that this is a duplicate of PR #683 which addresses a range of content including the text mentioned in this issue.  I will go ahead and close this one out.  Thanks for your patience on this Brian!
