### ISSUE TITLE
OS101 Module 4 Lesson 3 Typo

### ISSUE THREAD

**Issue by brian-knosp** [nasa/Transform-to-Open-Science#602]
Minor typo in the "Describing Our Code to Others" -> "Code Documentation" -> "Example" area where there's an extra period ('.'):

Descriptive variable, class, and function names can make your code very readable. . Sometimes even great coders are working fast and will name variables ‘a’, ‘temp’, or other names that probably won’t make a lot of sense in a week or two when they come back to something they were working on.

**Comment by bressler95tops** [comment]
Thank you Brian, for easy access I will reference this file here https://github.com/nasa/Transform-to-Open-Science/tree/main/docs/Area2_Capacity_Sharing/Open-Science-101/modules/Module_4/Lesson_3#code-documentation for changing on GitHub and the Curriculum

**Comment by katblanchette** [comment]
@bressler95tops - Please correct.

**Comment by bressler95tops** [comment]
@katblanchette @brian-knosp, It seems that there is a pull request that already includes this correction, this would be PR #661.  It would be better to address it there and close out this issue.
