### ISSUE TITLE
OS101 Module 5 Lesson 3 Typo

### ISSUE THREAD

**Issue by brian-knosp** [nasa/Transform-to-Open-Science#603]
Under "Capturing the Research Process Accurately in the Making of Results" there's a reminder of what we learned in the previous modules, but it refers to an "Open Software" module that has since been renamed "Open Code":

`In Open Software, you explored and identified the right tools and methods that ensure the usability and reproducibility of your analysis.`

**Comment by bressler95tops** [comment]
Thank you Brian makes sense to me.

**Comment by katblanchette** [comment]
@bressler95tops - Please correct. Thanks!

**Comment by bressler95tops** [comment]
Thank you @katblanchette. I can confirm that this is also a duplicate #683 and I will close this specific issue. @brian-knosp thank you for patience, feel free to let us know if you find any other instances of 'open software' that should be changed to 'open code'.

**Comment by katblanchette** [comment]
Thank you @bressler95tops and @brian-knosp, The OS101 Team has updated the Instructor Lead Training slides to reflect this change.
