### ISSUE TITLE
OS101 Module 2 Lesson 3: FTP and SFTP are no longer supported by NASA IT

### ISSUE THREAD

**Issue by mstudinger** [nasa/Transform-to-Open-Science#609]
Module 2 Lesson 3 lists FTP and SFTP as "current enabling tech". NASA IT has blocked FTP and SFTP ports over 10 years ago and we can't use these protocols anymore. I suggest they should not be listed as enabling technologies here.
 
https://github.com/nasa/Transform-to-Open-Science/tree/open-science-101/Module_2/Lesson_3

**Comment by bressler95tops** [comment]
Thank you, we will review your changes within the next week or two as finalize details for citing the curriculum.

**Comment by bressler95tops** [comment]
@katblanchette maybe you have flagged this one for further review.  But my first instinct if it helps is, yes I think that is true for NASA.  But since this course is available to everyone, my experience with FTP and SFTP is they are still pretty widely used, at least with LAMP stack builds.

**Comment by katblanchette** [comment]
@bressler95tops - Please add the following sentence after "Note that Microsoft Exchange Server and Skype are examples of proprietary protocols." New sentence "As always, it is necessary to balance accessibility with security concerns, which may impact the chosen protocol."

**Comment by bressler95tops** [comment]
Thank you @katblanchette I have addressed the issue in M2L3. For your reference (and for the MOOC developers) you may look at PR #800 to see the exact change. The exact text change is [under the files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/800/files) of the referenced Pull Request. Let me know when you are able to get that updated on the MOOC.

**Comment by bressler95tops** [comment]
Closing this issue as a solution has already been implemented.  You can see our reasoning in the above conversation @katblanchette @mstudinger.  Do feel free to bring any other issues to our attention.
