### ISSUE TITLE
What creative commons license is best for government created content?

### ISSUE THREAD

**Issue by cgentemann** [nasa/Transform-to-Open-Science#61]
CC-0, CC-BY, ? 
Reports, presentations, videos, data. What licenses can be applied and to what content?
Is it different when vendor produced versus gov. employee?

**Comment by libcce** [comment]
Chelle here is a decision from the EC https://creativecommons.org/2019/04/02/european-commission-adopts-cc-by-and-cc0-for-sharing-information/ to use both CC0 and CC-BY. I was trying to find a resource that discusses what I've heard from EU colleagues that even with something being CC0, services will try to apply CC-BY for attribution. @selgebali might be able to reference a resource here.

**Comment by jhkennedy** [comment]
We're also seeing some model data (e.g., [CMIP6](https://pcmdi.llnl.gov/CMIP6/TermsOfUse/TermsOfUse6-1.html) be licensed with CC BY-SA 3.0 license which imposes:

```
ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.
```
And it's unclear whether any *publication* using that data would also need to be released with the same license, and what *journals* are willing to publish with that license.

**Comment by nasacrawford** [comment]
We are currently developing guidance for this in SMD, but my current advice is:

At this time, NASA does not have a license for data.  Until further guidance is provided, the recommendation for scientific data produced by SMD that does not have any other limitations is to be released under a CC0 or equivalent license.  If there is an underlying license due to the data depending on another source, that license should be respected.  It is still recommended that even if it is licensed as CC0, users should give attribution when appropriate.

**Comment by leouieda** [comment]
> what journals are willing to publish with that license.

That's a very good question. A paper that uses a CC-BY-SA dataset to generate figures and new knowledge could be interpreted as "build upon the material" and the SA clause could end up hindering publication (for example, if one doesn't have funds for APCs and would go the green OA path). Assuming this is true, SA is detriment to the R in FAIR (reusable).

After reading this, I will probably avoid using CC-BY-SA data in the future to avoid possible headaches. It's the same issue as BSD/MIT vs GPL, where a lot of groups shy away from GPL software to be safe.

**Comment by nasacrawford** [comment]
[Fair use is still applicable to a Creative Commons license](https://creativecommons.org/faq/#do-creative-commons-licenses-affect-exceptions-and-limitations-to-copyright-such-as-fair-dealing-and-fair-use), and in general, usage for scientific purposes is considered fair use.
