### ISSUE TITLE
OS101 Module 4 Lesson 5: suggestion to fix issue with language

### ISSUE THREAD

**Issue by mstudinger** [nasa/Transform-to-Open-Science#610]
In Lesson 5 (From Theory to Practice) there is the following statement in the section "Contribute to Open-Source Software":
"...have discovered a particularly uninformative error message, be **colorblind** or be otherwise able..."

As a person with color vision deficiency (CVD) I suggest using more neutral language instead of "colorblind".

**Comment by bressler95tops** [comment]
Thank you, we will review your changes within the next week or two as finalize details for citing the curriculum.

**Comment by katblanchette** [comment]
@mstudinger  - Hi Michael - Thank you for your comment. Our OS101 is open to new language and would welcome your thoughts. Will you please share a recommended new sentence with us? Thank you!

**Comment by katblanchette** [comment]
@bressler95tops - The OS101 Team would like to change the sentence to ...Reporting an issue is a valuable contribution even if you don’t know how to fix it. For example, you might be using a different browser in which the software has not been tested yet, have discovered a particularly uninformative error message, or be unable to feed a valuable user experience back to the developers that can help to improve the overall usability of the software."

**Comment by bressler95tops** [comment]
Thank you @katblanchette I have addressed the issue in M4L5. For your reference (and for the MOOC developers) you may look at PR #767 to see the exact change. The exact text change is under the [files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/767/files) of the referenced Pull Request. Let me know when you are able to get that updated on the MOOC.

**Comment by bressler95tops** [comment]
@mstudinger @katblanchette our agreed upon changes are completed on the MOOC and GitHub.  Thank you for your contribution, feel free to submit more we always appreciate it!  I will be closing this issue out as resolved.
