### ISSUE TITLE
OS101 Module 1, Lesson 1: Broken Link 

### ISSUE THREAD

**Issue by lauracion** [nasa/Transform-to-Open-Science#623]
The [Ethical Source](https://ethicalsource.dev/community-code-of-conduct/) link in this [file](https://github.com/nasa/Transform-to-Open-Science/blob/open-science-101/Module_1/Lesson_1/readme.md) takes me to a page not found.

**Comment by bressler95tops** [comment]
Thank you for the feedback, we will review your changes within the next week or two as we finalize details for citing the curriculum.

**Comment by katblanchette** [comment]
@bressler95tops  - These pages are not found. Is this still an issue?

**Comment by bressler95tops** [comment]
@katblanchette, the [updated link is here](https://github.com/nasa/Transform-to-Open-Science/blob/open-science-101/Module_1/Lesson_1/readme.md) since this was before we moved the curriculum to its own branch for release.  I will update Laura's comment as well for consistency.

**Comment by katblanchette** [comment]
@bressler95tops - Please replace the broken link with this link: https://ethicalsource.dev/

**Comment by bressler95tops** [comment]
Thank you @katblanchette I have addressed the issue in M1L1. For your reference (and for the MOOC developers) you may look at PR #758 to see the exact change. The exact text change is [under the files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/758/files) of the referenced Pull Request. Let me know when you are able to get that updated on the MOOC.

**Comment by katblanchette** [comment]
@bressler95tops - Thank you for updating the content. I have shared this information with the MOOC developers and will notify you when the change is made.

**Comment by bressler95tops** [comment]
Thank you for your patience @lauracion @katblanchette this issue is completed on both the MOOC and on GitHub.  We always appreciate your feedback! I will mark this as completed.
