### ISSUE TITLE
OS101 Module 2, Lesson 2, image22 could be improved

### ISSUE THREAD

**Issue by lauracion** [nasa/Transform-to-Open-Science#625]
In [this image](https://github.com/nasa/Transform-to-Open-Science/blob/open-science-101/Module_2/images/media/image22.png) in Module 2, Lesson 2:
* The NASA TOPS logo is incomplete in the upper right margin
* The word ORCID is unnecessarily underlined
* it is difficult to follow each example; maybe consider the use of bullets for each example in the image?

**Comment by bressler95tops** [comment]
Thank you for pointing that out @lauracion.  We will be reviewing curriculum suggestions hopefully within the next week or two as we make some final adjustments to the release and citation information so definitely let us know if you find anything else and stay tuned.

**Comment by katblanchette** [comment]
@bressler95tops - the page is no longer found. Is this still an issue?

**Comment by bressler95tops** [comment]
Thanks for pointing this out @katblanchette, this was posted before we came up with our release process, so it has [moved to this link](https://github.com/nasa/Transform-to-Open-Science/blob/open-science-101/Module_2/images/media/image22.jpeg).

**Comment by bressler95tops** [comment]
I have updated Laura's comment to reflect this, if I see any other ones that might have moved, I will do the same.

**Comment by katblanchette** [comment]
@bressler95tops and @lauracion - Thank you for your information and details about the graphic. I have reached out to our graphic designer and asked for a new image. Stay tuned.

**Comment by bressler95tops** [comment]
Thank you [@katblanchette](https://github.com/katblanchette) and @lauracion for you patience. I have addressed the image in M2L2. For your reference (and for the MOOC developers) you may look at PR #765 to see the exact change. The exact text change is [under the files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/765/files) of the referenced Pull Request. Let me know when you are able to get that updated on the MOOC.

**Comment by bressler95tops** [comment]
Thank you for your patience @lauracion and @katblanchette these changes are live in both the MOOC and on GitHub and this Issue can be marked as closed.
