### ISSUE TITLE
OS 101 module 1 lesson 3: confusion about copyright vs licensing

### ISSUE THREAD

**Issue by danielskatz** [nasa/Transform-to-Open-Science#632]
In module 1, lesson 3, I read
> As we’ve previously shown, different kinds of intellectual property are released using different formal structures. For example, text and media products are released under copyright and software is released under a license.

However, copyright and licensing are general concepts that apply to all IP, I believe. At least text, images, software, and data all typically have a copyright (ownership) as well as license (usage). The licenses might vary, but they still apply to all types of IP.

**Comment by danielskatz** [comment]
One of the questions at the end of this lesson includes this text about copyright

>It gives permission to apply for a license but is not, itself, a type of license.

which I also don't think is exactly correct. Copyright is ownership, and the owner can apply a license, so in some sense copyright says who can apply a license, but it's not really giving permission to "apply **for** a license"

**Comment by danielskatz** [comment]
This confusing text is also in the assessment at the end of the entire module: "It [copyright] gives permission to apply for a license"

**Comment by bressler95tops** [comment]
Thank you for pointing that out @danielskatz. We will be reviewing curriculum suggestions hopefully within the next couple weeks as we make some adjustments to the first release and citation information so definitely let us know if you find anything else and stay tuned.  I also see you made some other suggestions so I will flag these for review as well.

**Comment by danielskatz** [comment]
Thanks - I'm just making comments as I go through this, which are my opinions on first seeing the material. Feel free to do whatever makes sense, including making changes, ignoring my opinions as not those of others, etc.

**Comment by bressler95tops** [comment]
@katblanchette Not sure if you had already seen these but if not, let me know if you think they should be addressed.

For the first additional comment, it seems to be the text when you choose the correct answer in the lesson knowledge check. 
![comment1](https://github.com/nasa/Transform-to-Open-Science/assets/137207208/98d9c84d-a386-4247-9010-08aca51c4162)

For the second additional comment, it also seems to be the status message when you choose the correct answer in the module assessment, this is not present on GitHub since we don't provide the assessment but maybe it should revised there.
![comment2](https://github.com/nasa/Transform-to-Open-Science/assets/137207208/f6cdc4cb-72b6-4213-bdec-d9108899ced4)

**Comment by bressler95tops** [comment]
Otherwise, I have addressed the main issue mentioned in PR #759. The exact text change is [under the files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/759/files) of the referenced Pull Request. Let me know when you are able to get that updated on the MOOC.

**Comment by katblanchette** [comment]
@bressler95tops and @danielskatz - Thank you for the content updates and clarifications! Regarding, the MOOC's Module 1 assessment, I have located the question within M1's MOOC assessment and will add this update in text to the Developer's update list. @danielskatz - Double checking with you for your thoughts, should the correct answer read... "Copyright gives permission to apply for a license but is not, itself, a type of license."?

**Comment by danielskatz** [comment]
Not exactly.  Here's what I would say instead

"Copyright gives permission to apply a license but is not, itself, a type of license."

Basically, copyright is ownership (more or less), and the owner can select and apply a license, with some caveats that aren't important to get into at this level.

**Comment by katblanchette** [comment]
Thank you @danielskatz, that is a good sentence, and I will add it to the MOOC Developers list to update.

**Comment by bressler95tops** [comment]
@danielskatz @katblanchette thank you for your patience, this is now addressed both here on GitHub (where relevant as the assessments don't currently exist on the GitHub version of OS101) and on the MOOC.
