### ISSUE TITLE
OS 101 Module 2 lesson 1: open research products is too limited

### ISSUE THREAD

**Issue by danielskatz** [nasa/Transform-to-Open-Science#634]
While data, code/software, and results are the primary products of computational research, other types of research might have other products as well, perhaps including algorithms, methods, physical artifacts, ...  Perhaps you consider all of these results?

**Comment by katblanchette** [comment]
Update: Add this sentence under the "Open Research Products"  Venn Diagram, "Within these research products are additional types of products, such as methodologies, algorithms, and physical artifacts."

**Comment by bressler95tops** [comment]
Thank you @katblanchette I have addressed the issue in M2L1. For your reference (and for the MOOC developers) you may look at PR #764 to see the exact change. The exact text change is under the [files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/764/files) of the referenced Pull Request. Let me know when you are able to get that updated on the MOOC.

**Comment by bressler95tops** [comment]
@danielskatz @katblanchette thank you for your patience, this change has been made on both the MOOC and GitHub and can now be marked as closed.  Do feel free to open another issue if you find anything else.
