### ISSUE TITLE
OS 101 Module 2, lesson 2: minor comments

### ISSUE THREAD

**Issue by danielskatz** [nasa/Transform-to-Open-Science#635]
"Similar to tax ID numbers for tax purposes" might be better as "Used similarly to how tax ID numbers are used for tax purposes"

"It is a 16-digit number" - actually, ORCIDs aren't always numbers, as they can sometimes include characters.

"e.g. career change or name change" is missing a comma - "e.g., career change or name change"

I wonder if you should point out that PIDs are as much cultural agreements on how people and systems should behave as they are infrastructure.

"e.g. as a README file or user guide" should be "e.g., as a README file or user guide"

"a software management plan for SMD-funded research should include" - I'm not sure SMD has been introduced at this point, but even if so, most non-NASA readers won't know what this is here.

**Comment by katblanchette** [comment]
@bressler95tops :
1st comment - please change
2nd comment - No changes, and here is the reasoning: https://support.orcid.org/hc/en-us/articles/360006897674-Structure-of-the-ORCID-Identifier.
3rd comment - please change.
4th comment - We do not want to make this change; however it allowed us to notice a grammatical error in the sentence. Please update the sentence to "A digital persistent identifier (or "PID") is a “long-lasting reference to a digital resource” that is machine-readable and uniquely points to a digital entity, according to [ORCID](https://support.orcid.org/hc/en-us/articles/360006971013-What-are-persistent-identifiers-PIDs-). Examples of persistent identifiers used in science are described below."
5th comment - please change
6th comment - please update and spell out SMD to NASA Science Mission Directorate (SMD).

**Comment by danielskatz** [comment]
re the second comment, I'm unsure how "X" is a number, unless we've gone back to the Roman system :)

**Comment by katblanchette** [comment]
@danielskatz - Great point. :) We will gladly update the language if ORCID does. Until then, we will continue to describe it as they have.

**Comment by bressler95tops** [comment]
@katblanchette comment 5 appeared to be good already.  So I would look out to see if this is something that might have only been broken on the MOOC.  Other than that, I have addressed as requested in PR #775. The link to the files changed tab [is here](https://github.com/nasa/Transform-to-Open-Science/pull/775/files) for precise comparison.  Let me know when the MOOC developers have had an opportunity to implement.

**Comment by itcarroll** [comment]
> re the second comment, I'm unsure how "X" is a number, unless we've gone back to the Roman system :)

😆 Seems like that's actually what they did: https://support.orcid.org/hc/en-us/articles/360006897674-Structure-of-the-ORCID-Identifier#2-checksum

**Comment by danielskatz** [comment]
Yes, I understand, and that was why I said that, but I don't think the average person thinks of "X" as a number...

**Comment by bressler95tops** [comment]
@danielskatz @katblanchette thank you for your patience.  I had to make a minor change, I accidentally repeated some words but the change was already correct on the MOOC.  So I made that correction and now the MOOC and GitHub should both have the appropriate change and I can mark this as closed.
