### ISSUE TITLE
OS 101 module 2 lesson 3: garbled bullet point

### ISSUE THREAD

**Issue by mstudinger** [nasa/Transform-to-Open-Science#642]
This is a garbled sentence that should be fixed:
"List and explain the purpose of the resources commonly used in making data including the data formats, inspecting data, and assessing ‘FAIR’-ness of data."

**Comment by bressler95tops** [comment]
Thank you for pointing that out @mstudinger. We will be reviewing curriculum suggestions hopefully within the next couple weeks as we make some adjustments to the first release and citation information so definitely let us know if you find anything else and stay tuned.

**Comment by katblanchette** [comment]
@bressler95tops - Update: Replace sentence with this sentence: "List and explain the resources commonly used in making data, including formatting, inspecting, and assessing the ‘FAIR’-ness of data."

**Comment by bressler95tops** [comment]
Thank you @katblanchette I have addressed the issue in M2L3. For your reference (and for the MOOC developers) you may look at PR #763 to see the exact change. The exact text change is under the [files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/763/files) of the referenced Pull Request. Let me know when you are able to get that updated on the MOOC.

**Comment by bressler95tops** [comment]
@mstudinger @katblanchette thank you for your patience, this change is completed on both the MOOC and GitHub and this issue can now be closed.
