### ISSUE TITLE
OS 101 module 2 lesson 3: suggestions to align module data format content with NASA data standard requirements

### ISSUE THREAD

**Issue by mstudinger** [nasa/Transform-to-Open-Science#643]
Since this is a NASA course I suggest the contents about data formats should be made compatible with NASA standard data format requirements, which are BTW often spelled out in ROSES Data Management Plan requirements (this course mentions DMPs quite a bit). I am familiar with the Earth science data requirements, but am guessing there are more: https://www.earthdata.nasa.gov/esdis/esco/standards-and-practices
NB: XML and JSON are not approved NASA data standards.

**Comment by bressler95tops** [comment]
@mstudinger thank you for your patience, we are just getting around to this issue.  We dispositioned this to the project office, headquarters, and others which you may have seen. We have decided that while this true for some divisions of NASA, it's not necessarily the case for other divisions of NASA, and external researchers who still widely use the technologies.  At this time we will not be proceeding with a fix for this.  Thank you.
