### ISSUE TITLE
Note about Q1 in Knowledge Check for OS101 M4 L1

### ISSUE THREAD

**Issue by TomLav** [nasa/Transform-to-Open-Science#646]
Dear OS101 developers,

I took the curriculum earlier this year, and learned a lot. Thank you very much for this resource.

As I was re-reading my notes, I remembered that the answer to Question 1 of the Knowledge Check for M4 L1 (Introduction to Open Code) had not seemed obvious to me. Here, I respectfully suggest a re-wording of the question. 

The [question](https://github.com/nasa/Transform-to-Open-Science/blob/a3a71c7251da7dea104dbdae07941c6d956dcecb/docs/Area2_Capacity_Sharing/Open-Science-101/modules/Module_4/Lesson_1/readme.md?plain=1#L343) is to decide if the following statement is True or False:

*Software is referred to as open source when it is publicly accessible; anyone can see, modify, and distribute the code as they see fit.*

My issue comes from the end of this statement "as they see fit", that I understand as a non-restrictive, absolute right to modify and distribute the code. However, as covered in the course, the license is a key element of open source software, and some licenses do restrict how software can be modified or distributed (or at least how modified versions of the code can be distributed)?

To me, the answer would thus have been more correct if the statement had read:

*Software is referred to as open source when it is publicly accessible; anyone can see, modify, and distribute the code as they see fit within the constraints set by the software license.* (or any better formulation).

Or course, the above might just stems from my lack of expertise with OSS and licenses in general. In which case, I'll have to take this module again...

If I remember correctly, the same question is in the final quiz for module 4, and I got it wrong there, again because of the license.

**Comment by bressler95tops** [comment]
thank you @TomLav feel free to let us know if you find anything else!

For future reference, we just recently released OS101 for citations and this has caused a few things to change here on GitHub. We now have new guidance that is located [here](https://github.com/nasa/Transform-to-Open-Science/blob/main/CONTRIBUTING.md#contributing-to-open-science-101-on-github) and will be reviewing all the great feedback we received over the next few weeks as we determine standard processes.

The biggest change right now is that we have relocated the [curriculum files here](https://github.com/nasa/Transform-to-Open-Science/tree/open-science-101) to make it more accessible and move it out of the directory it was nested in.  This also allows it to be more adapted for routine releases on Zenodo.

Thank you and let me know if you have any questions.

**Comment by katblanchette** [comment]
@bressler95tops - Update #1: In the Knowledge Check of M4, L1 add the words, "within the constraints set by the software license.", at the end of the sentence, beginning with "Software is referred to as open source when it is publicly accessible; anyone can see, modify, and distribute the code as they see fit." . Update #2: In the Assessment of M4,  add the words, "within the constraints set by the software license.", at the end of the sentence beginning with "Software is referred to as open source when it is publicly accessible; anyone can see, modify, and distribute the code as they see fit." .

**Comment by bressler95tops** [comment]
Thank you @katblanchette I have addressed the issue in the knowledge check of M4L1, for your reference (or the reference of the MOOC developers) you may look at PR #746 to ensure the change matches.  As for the final assessment of M4, that is not included in this public version so that would have to be addressed on the MOOC.

**Comment by bressler95tops** [comment]
@TomLav @katblanchette thank you for your patience, this issue has been addressed on both the MOOC and on the GitHub version of OS101 and can now be marked as closed.
