### ISSUE TITLE
Missing link Lesson 2 Module 1 Benefits to you

### ISSUE THREAD

**Issue by rebeccaringuette** [nasa/Transform-to-Open-Science#650]
In the 'Benefits to You' section, the link in the following text is missing.
Articles that make their data openly accessible via a direct link to a repository see ~25% higher citation impact, according to a 2020 study. 
The link should be to this paper.
Citation: Colavizza G, Hrynaszkiewicz I, Staden I,
Whitaker K, McGillivray B (2020) The citation
advantage of linking publications to research data.
PLoS ONE 15(4): e0230416. https://doi.org/
10.1371/journal.pone.0230416

The text in the previous paragraph in the material has the link to the paper above:
"Publishing open access increases citation count by 18%, according to a 2018 [study(opens in a new tab)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7176083/)."

The 2018 study obviously was not published in 2020. The study could be the one below, especially since is has the 18% increase comment in the abstract. However, the study was quite limited, and there may be better choices.
- Piwowar H, Priem J, Larivière V, Alperin JP, Matthias L, Norlander B, Farley A, West J, Haustein S. 2018. The state of OA: a large-scale analysis of the prevalence and impact of Open Access articles. PeerJ 6:e4375 https://doi.org/10.7717/peerj.4375

**Comment by bressler95tops** [comment]
thank you @rebeccaringuette feel free to let us know if you find anything else!

For future reference, we just recently released OS101 for citations and this has caused a few things to change here on GitHub with the development version of the curriculum. We now have new guidance that is located [here](https://github.com/nasa/Transform-to-Open-Science/blob/main/CONTRIBUTING.md#contributing-to-open-science-101-on-github) and will be reviewing all the great feedback we received over the next few weeks as we determine standard processes.

You can keep making suggestions the way you have been, but the biggest change right now is that we have relocated the files for the development version [here](https://github.com/nasa/Transform-to-Open-Science/tree/open-science-101) to facilitate the process.  The location at openscience.org will of course be the same to get badged.

Thank you and let me know if you have any questions.

**Comment by katblanchette** [comment]
@bressler95tops - 1st Update: Replace the 2018 study link with this link - https://peerj.com/articles/4375/. 2nd Update: Add the hyperlink https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7176083/,  to the word "Study" in the sentence beginning with "Articles that make their data openly accessible via a direct link to a repository see ~25% higher citation impact, according to a 2020 study."

**Comment by bressler95tops** [comment]
@katblanchette I realized that this is actually in reference to Module 1 and not Module 3.  I made sure to double check on the MOOC to ensure it wasn't something on my end and it matches up.  I went ahead and made those revisions in PR #747.  The exact text change can be found in the ['Files Changed' tab](https://github.com/nasa/Transform-to-Open-Science/pull/747/files).

**Comment by katblanchette** [comment]
@bressler95tops - Thank you for the updates. I have also updated the ILT slide deck and added this to the list of updates for the MOOC Developer. I will notify you when the updates are finalized.

**Comment by bressler95tops** [comment]
@rebeccaringuette @katblanchette thank you for your patience.  The fixes have been applied on both the GitHub version of the curriculum and the OS101 MOOC and this issue can now be marked as closed.
