### ISSUE TITLE
Numerous error in text

### ISSUE THREAD

**Issue by rebeccaringuette** [nasa/Transform-to-Open-Science#656]
There are numerous errors in the text of all of the modules, such as misspelled words, broken links, and grammatical errors. There needs to be a revision performed to correct those errors. Leaving them in the material is not the ideal image to project for NASA TOPS.

**Comment by bressler95tops** [comment]
Thank you Rebecca we have received a number of requests noting improvements to grammar and corrections to errors and we do hear your concerns.  Our plan at this moment is to follow a standard software release cycle where our [development version](https://github.com/nasa/Transform-to-Open-Science/tree/open-science-101) of the curriculum will receive consistent updates based on feedback.  The review process of these updates is currently in planning so expect current feedback to make its way into the [development version](https://github.com/nasa/Transform-to-Open-Science/tree/open-science-101) very soon.

The other side to this is those suggestions will make their way into our [MOOC](https://openscience101.org/) in the next version release which will happen on a specific cadence (which according to our [FAQs](https://github.com/nasa/Transform-to-Open-Science/blob/main/tops_faq.md )is every 6 months).

Given these things, we highly encourage you to submit issues or pull requests to point out any areas that you have found with problematic text.  There is more guidance on contributing [here](https://github.com/nasa/Transform-to-Open-Science/blob/main/CONTRIBUTING.md#contributing-to-open-science-101-on-github).

**Comment by bressler95tops** [comment]
@rebeccaringuette several issues and pull requests are now being worked into the GitHub version of OS101 and within the MOOC.  While there may be more corrections down the line, it should be a pretty notable improvement over the first version once changes go live everywhere.  I will likewise consider this issue closed, but we always welcome more suggestions if you find anything specific that needs fixing.

**Comment by rebeccaringuette** [comment]
Sounds great. Thanks!
When is the next version expected?

**Comment by bressler95tops** [comment]
> Sounds great. Thanks! When is the next version expected?

As of writing, this is TBD.  This should in theory follow a 6-month cadence from the last version release, but since we are just rolling out our review process, the coming version release will likely need some additional planning.  We will definitely make an announcement on GitHub when we are ready with this.
