### ISSUE TITLE
Module 3 Lesson 2 - Apparently misplaced text

### ISSUE THREAD

**Issue by SLLDeC** [nasa/Transform-to-Open-Science#658]
The following text presented in Module 3, Lesson 2, *Section People You Know (Online or In-person!)*  [here](https://github.com/nasa/Transform-to-Open-Science/tree/open-science-101/Module_3/Lesson_2) seems misplaced. I am lost at its relationship with the rest of the content.

> When we show up to the present moment with all of our senses, we invite the world to fill us with joy. The pains of the past are behind us. The future has yet to unfold. But the now is full of beauty simply waiting for our attention.

**Comment by bressler95tops** [comment]
thank you @SLLDeC I did see this mentioned before after the release, I will flag this for review but this does make sense to me, it seems to be placeholder text that wasn't caught.  We should be reviewing all our great suggestions from our community within the coming weeks as we determine standard processes.

**Comment by katblanchette** [comment]
@bressler95tops - Please correct

**Comment by bressler95tops** [comment]
@katblanchette actually seems to be addressed already with PR #600

**Comment by bressler95tops** [comment]
I can go ahead and close this one out
