### ISSUE TITLE
OS101 Module 4 Lesson 4 Step 6 (Mobile version): "How: How to Enable Reuse of Code" content is not navigable

### ISSUE THREAD

**Issue by 4iro** [nasa/Transform-to-Open-Science#672]
(Mobile version issue) The module cannot be completed due to a blocking issue. It is not possible to scroll down through "How: How to Enable Reuse of Code".  

Tested on:  
Xiaomi 11 Lite. Chrome
Samsung Galaxy A51. Chrome

![Screenshot_2024-02-16-11-39-20-181_com android chrome](https://github.com/nasa/Transform-to-Open-Science/assets/45294097/891b663c-d027-4296-a97d-5feb419b83e6)

Please let me know if you need more info.

**Comment by katblanchette** [comment]
@bressler95tops  - This is a MOOC issue and has since been corrected.

**Comment by bressler95tops** [comment]
Thank you @katblanchette I will mark this as completed.  @4iro thank you for your patience, this has since been resolved.
