### ISSUE TITLE
OS101 Module 3 Lesson 5 - typos in example ThEBES DMP

### ISSUE THREAD

**Issue by NicolePV** [nasa/Transform-to-Open-Science#682]
In "Writing an Open Science and DMP", Activity 5.1,  Thermal_Effects_of_Bombardment_in_the_Early_Solar_System_(ThEBES).pdf

In the example ThEBES DMP PDF file, there are two small typos that could be corrected. 

Page 2, paragraph 3, near end of line 1: 
"workd" should be "work"

Page 2, paragraph 3, at end of line 3: 
"ArXiv-ASTRO-PHY" should probably be "ArXiv-ASTRO-PH"

And a small suggestion:

Page 2, paragraph 5, line 2:
"CUB" is undefined; suggest updating to "University of Colorado" to match similar references in text

**Comment by bressler95tops** [comment]
Thank you @NicolePV so this document is something that we do not control.  But your corrections are very reasonable.  I will see if this is something I can reach out to them about

**Comment by bressler95tops** [comment]
Tracking this issue [here ](https://github.com/CDLUC3/dmptool/issues/536) as I located their repository.

**Comment by bressler95tops** [comment]
Dmptool got back to me and pointed out that making corrections to the document would require reaching out to the original author as they only provide a service to upload DMPs.  I can attempt to contact them citing this issue.

**Comment by katblanchette** [comment]
@bressler95tops - Please correct.

**Comment by bressler95tops** [comment]
Thanks @katblanchette, I will try to reach out to the author the author of the DMP to see if they would be willing to make that change.  Otherwise, we may need to figure out an alternative.

**Comment by bressler95tops** [comment]
Thanks @katblanchette, I will try to reach out to the author the author of the DMP to see if they would be willing to make that change.  Otherwise, we may need to figure out an alternative.

**Comment by cgentemann** [comment]
We have reached out and let them know. Thank you!!
