### ISSUE TITLE
OS101 Module 4 Lesson 3 - small issue under Programming Best Practices

### ISSUE THREAD

**Issue by NicolePV** [nasa/Transform-to-Open-Science#693]
In the table labelled "Additional Helpful Tips", there are two entries that seem very similar.

Operation Documentation
Share details about how you are running the code. For example, document the version of a software library you are using, or the version of the compiler. These are often shared in an 'environment.yml' file.

Portability
Share details about how you are running the code, for example the version of a software library you are using, or the version of the compiler. These are often shared in an ‘environment.yml’ file.

Perhaps the text under Portability is an initial copy of the Operation Documentation text that should have been updated with new content.

**Comment by katblanchette** [comment]
@bressler95tops - Replace text with new text. Update: Replace the text under "Portability" with  ...  Allows individuals the ability to transfer their personal data between platforms.

**Comment by bressler95tops** [comment]
Thank you @katblanchette I have addressed the issue in M4L3. For your reference (and for the MOOC developers) you may look at PR #773 to see the exact change. The exact text change is under the [files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/773/files) of the referenced Pull Request. Let me know when you are able to get that updated on the MOOC.

**Comment by bressler95tops** [comment]
@NicolePV @katblanchette thank you for your patience, this change is complete on both the MOOC and on the GitHub version and can now be marked as closed.
