### ISSUE TITLE
OS101 Module 5 Lesson 1 - typo under Examples of Open Results

### ISSUE THREAD

**Issue by NicolePV** [nasa/Transform-to-Open-Science#694]
At the beginning (first sentence) of the section on New Products for Increasing Impact, there is a single quotation mark and a double quotation mark which frame a long phrase. I suspect that these two marks are partners and should share the same form. It is also not completely clear whether all of the long phrase should lie within the quotation marks, or whether they should frame a subsection of it.

Sentence:
From ‘2003: let’s map the UK to 2023:>1.5M contributors, 100M+ edits, using the data to map the world with applications ranging from Uber to mapping UN Sustainable Development Goals.”

Possible revised form:
From "2003: let’s map the UK to 2023: using the data to map the world with applications ranging from Uber to mapping UN Sustainable Development Goals." (>1.5M contributors, 100M+ edits)

It's possible that this text needs to be further revised, however. I'm not finding an original source online, if it is indeed a quotation from an online document. Or is it a title?

It's also possible that this sentence is an attribution note from the editor who created the text, one that was not meant to be included in the lesson proper.

**Comment by katblanchette** [comment]
@bressler95tops  - Please correct using revised text above. Thanks!

**Comment by bressler95tops** [comment]
@katblanchette I have addressed the issue in M5L1. For your reference (and for the MOOC developers) you may look at PR #768 to see the exact change. The exact text change is under the [files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/768/files) of the referenced Pull Request. Let me know when you are able to get that updated on the MOOC.

**Comment by bressler95tops** [comment]
@NicolePV @katblanchette thank you for your patience this change appears to be completed on both the MOOC and GitHub and can now be marked as closed. We appreciate your contributions to our curriculum!
