### ISSUE TITLE
Module 2 Lesson 1: bad DOI link

### ISSUE THREAD

**Issue by ritajett** [nasa/Transform-to-Open-Science#704]
<img width="708" alt="image" src="https://github.com/nasa/Transform-to-Open-Science/assets/43415378/3dbc713c-a8e8-4bae-8cb3-e3826ddd6621">

The second link listed to all versions for this software looks to be truncated (links to a DOI not found page).

**Comment by bressler95tops** [comment]
Thank you for submitting this suggestion @ritajett. We are actively working on a review process for OS101 and we should be reviewing these in the coming weeks. Stay tuned and feel free to keep submitting more suggestions in the meantime.

**Comment by katblanchette** [comment]
@bressler95tops  - Update: replace bad link with new link - https://zenodo.org/records/10161527.

**Comment by bressler95tops** [comment]
Thank you @katblanchette I have addressed the issue in M2L1. For your reference (and for the MOOC developers) you may look at PR #774 to see the exact change. The exact text change is [under the files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/774/files) of the referenced Pull Request. Let me know when you are able to get that updated on the MOOC.

**Comment by bressler95tops** [comment]
@ritajett @katblanchette thank you for your patience, this issue has been addressed on both the GitHub version of OS101 and the MOOC and can likewise be closed.  TOPS always appreciates your contributions to help make the curriculum even better!
