### ISSUE TITLE
Module 4, Lession 1: No distinction between operational software and infrastructure software

### ISSUE THREAD

**Issue by likeajumprope** [nasa/Transform-to-Open-Science#710]
In Module 4, Lession 1 (Open Software) there is no distinction between operational and infrastructure software:

"Operational Software – Operational software is used by data centers and large information technology facilities to provide data services."

"Infrastructure Software – Infrastructure software is used by data centers and large information technology facilities to provide data services."

**Comment by bressler95tops** [comment]
Thank you for submitting this suggestion about the Open Data module @likeajumprope . We are actively working on a review process for OS101 and we should be reviewing these in the coming weeks. Stay tuned and feel free to keep submitting more suggestions in the meantime!

**Comment by bressler95tops** [comment]
Thank you @katblanchette, I have addressed the issue in M4L1.  One thing to note is there are example bullets of specific software under these.  I assumed that I should keep them, but it is possible that the updated definitions might not match with them anymore.  Let me know if they should be removed or if they are good as it is.

For your reference (and for the MOOC developers) you may look at PR #766 to see the exact change. The exact text change is [under the files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/766/files) of the referenced Pull Request. Let me know when you are able to get that updated on the MOOC.

**Comment by bressler95tops** [comment]
@likeajumprope @katblanchette thank you for patience, this change has been completed on both the MOOC and the GitHub version of OS101.  As always we appreciate your contributions to our curriculum!
