### ISSUE TITLE
Word correction requested for graphic used for Mod 1 Lesson example on "Atmosphere Cooling" 

### ISSUE THREAD

**Issue by kyuenjpl** [nasa/Transform-to-Open-Science#719]
Atmospheric scientist pointed out the Module 1 lesson example on the global cooling error is confusing and not correct. 
On the chart, it makes the mention of the upper atmosphere cooling, but the data showed that it was actually warming. 

The original paper mentions looking at the upper troposphere (https://digitalcommons.unl.edu/cgi/viewcontent.cgi?article=1318&context=usdeptcommercepub). But the issue is the troposphere is the lowest part of the atmosphere. Upper atmosphere would be considered stratosphere and above. So with warming in the troposphere, there is actual _cooling_ of the upper atmosphere (stratosphere).
 
Suggestion from the PI is be precise and just say **troposphere** instead of atmosphere in the lesson example. We can add an asterisk or note to show where troposphere is (https://www.sciencefacts.net/layers-of-atmosphere.html)

We would need to make a change in the graphic.

**Comment by bressler95tops** [comment]
Thank you @kyuenjpl, I will add this suggestion to our review process. We are holding review meetings very soon and monthly thereafter. Stay tuned, as we get to your contribution. We greatly appreciate it and feel free to continue submitting suggestions.

**Comment by bressler95tops** [comment]
Agreed, I think this would add context for those who may not be as familiar with the subject matter.

**Comment by bressler95tops** [comment]
@katblanchette, I am just formally adding a comment that I have addressed the issue in M1L1. The newest image available is being used now. For your reference (and for the MOOC developers) you may look at PR #730 and #779. To see the exact change you can visit the 'files changed' tab on each of these links.

**Comment by katblanchette** [comment]
@bressler95tops - Will you update the graphic to this newer version? We modified the colors during the OSE development. https://drive.google.com/file/d/1AVzAee_-y-8-jJCMthjPxqgeMJyxOom_/view .Thank you!

**Comment by bressler95tops** [comment]
@kyuenjpl @katblanchette thank you for patience.  This change has been completed in both the MOOC and GitHub which includes changes from #824.  We always appreciate your contributions to OS101!
