### ISSUE TITLE
Module 3, Lesson 4: There is a broken link

### ISSUE THREAD

**Issue by gimwalli** [nasa/Transform-to-Open-Science#729]
The follow link is broken:
[Export Administration Regulations](https://www.bis.doc.gov/index.php/regulations/export-administration-regulations-ear) (EAR), which regulates the manufacture, sale, distribution, and export of commercial and dual- use items, technology, and information not already covered by ITAR.
String URL: https://crowdin.com/editor/nasatops-os101-es/240/en-es419?view=side-by-side#19296

**Comment by bressler95tops** [comment]
Thank you @gimwalli, we will add this to our queue for review, feel free to submit any other feedback!

**Comment by katblanchette** [comment]
@gimwalli - Good catch and thank you for the information. @bressler95tops - Please replace the broken link with https://www.bis.gov/regulations/ear-overview . Thank you!

**Comment by bressler95tops** [comment]
Thank you @katblanchette I have addressed the issue in M3L4. For your reference (and for the MOOC developers) you may look at PR #808 to see the exact change. The exact text change is [under the files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/808/files) of the referenced Pull Request. Let me know when you are able to get that updated on the MOOC.

**Comment by katblanchette** [comment]
@bressler95tops - Thank you! The changes look correct. I have updated the issue to "Complete" on our internal tracking document.

**Comment by bressler95tops** [comment]
@katblanchette PR #898 readdresses the broken link

**Comment by bressler95tops** [comment]
@gimwalli @katblanchette thank you for your patience, this issue is addressed on both the MOOC and the GitHub version of the curriculum and can now be closed.  We appreciate your feedback that is helping improve our curriculum!
