### ISSUE TITLE
OS101 Module 5 Lesson 3 Ethics Review definition

### ISSUE THREAD

**Issue by 4N0NYM0U5MY7H** [nasa/Transform-to-Open-Science#750]
The language of the current definition appears incomplete:
https://github.com/nasa/Transform-to-Open-Science/blob/8b39d3357d2d3d7e26480e1860fd7cd231b07a94/Module_5/Lesson_3/readme.md?plain=1#L419

Perhaps I am misinterpreting?

Potential fix:
"Verify whether the research project needs to undergo an ethics review process"

**Comment by katblanchette** [comment]
@4N0NYM0U5MY7H  - Good catch and thank you for input! @bressler95tops - please replace the definition of Ethics Review with this sentence ... "Verify whether the research project needs to undergo an ethics review process".

**Comment by bressler95tops** [comment]
Thank you @4N0NYM0U5MY7H for creating that pull request I have merged it in.  @katblanchette, we can call this one completed likewise.  The PR that was merged in is PR #804.  You can have a look at the ['files changed'](https://github.com/nasa/Transform-to-Open-Science/pull/804/files) tab to have a look at the precise change as usual.  Let me know when the MOOC developers have had a change to implement this.

**Comment by katblanchette** [comment]
@bressler95tops - Thank you! The changes look correct. I have updated the issue to "Complete" on our internal tracking document.

**Comment by bressler95tops** [comment]
@4N0NYM0U5MY7H @katblanchette thank you for patience.  This change has been implemented both on the GitHub version of OS101 and on the MOOC and likewise this issue can now be closed.  We appreciate your feedback as always.
