### ISSUE TITLE
OS 101 module 3 welcome - dealing with the fact that raw data (facts) isn't copyrightable

### ISSUE THREAD

**Issue by danielskatz** [nasa/Transform-to-Open-Science#781]
I feel that the terms are not quite right in terms of the fact that data itself isn't subject to copyright.

Copyright here says "Many different types of works are covered by copyright law including data products" which is correct, but perhaps should include something like "Note: raw data (facts) is not covered by copyright law."

The next item, "Data" includes "observable facts", which would not be subject to copyright.

There is no term "data products" though it is mentioned in the Copyright term.

The Data License definition also misses the fact that raw data doesn't need a license, as it's not not subject to copyright to start with.

**Comment by bressler95tops** [comment]
Thanks for the contribution @danielskatz we will add this to our queue for review.  Right off the bat, I can see this shares in part what PR #785 has suggested.  I would be curious to know if you believe the change in phrasing resolves your comment about the definition of "Data" given that it is more specific about the type of factual information.  This will help us during our review of this issue as a whole.

**Comment by danielskatz** [comment]
I don't disagree with the change you mention, but the other points I've made still stand, even with that change.

**Comment by bressler95tops** [comment]
Yes agreed, that would only address that specific part of it if anything, just wanted to know what your thoughts were on it since it was related.  We will definitely be reviewing your suggestions as a whole.

**Comment by katblanchette** [comment]
@bressler95tops  - Please make the following additions to the content. 1. Add the sentence into the "Copyright" definition, near the end of the definition ...""Note: Raw data, which are considered facts, are not covered by copyright law." 2. Add the definition of Data Products. New definition - Data Products are reusable assets that process data and generate insights that help organizations make better decisions. Data products can include datasets, data streams, data feeds, APIs, code, data models, analytics models, and dashboards. 3. Add the sentence into the "Data License" definition, near the end of the definition ...""Note: Raw data are not covered by copyright law."

**Comment by bressler95tops** [comment]
Thank you @katblanchette I have addressed the issue in the M3 welcome readme file. For your reference (and for the MOOC developers) you may look at PR #807 to see the exact change. The exact text change is [under the files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/807/files) of the referenced Pull Request. Let me know when you are able to get that updated on the MOOC.

**Comment by katblanchette** [comment]
@bressler95tops - Thank you! The changes look correct. I have updated the issue to "Complete" on our internal tracking document.

**Comment by bressler95tops** [comment]
@danielskatz @katblanchette thank you for patience, this change appears to be implemented in both the MOOC and on the GitHub version of the curriculum. Likewise, this issue can now be closed.  As always, we appreciate your feedback!
