### ISSUE TITLE
Disclaimer about Paid Articles Links

### ISSUE THREAD

**Issue by katblanchette** [nasa/Transform-to-Open-Science#792]
@bressler95tops Addition: To be located under the last sentence in the About This Module (highlighted section, black text that matches existing text). Add the disclaimer within [M1](https://github.com/nasa/Transform-to-Open-Science/tree/open-science-101/Module_1), M2, M3, M4, and M5 

Disclaimer: Please note that we reference several papers throughout the course and depending on the paper, it might be blocked by a paywall. If you would like to get a copy of the paper, please contact the Author or search for it in an online preprint archive. For example, [bioRxiv.org](http://biorxiv.org/). 

![About the Module](https://github.com/user-attachments/assets/66150e0e-0d96-4e21-8cb4-df559cd4da0b)

**Comment by nasacrawford** [comment]
Since we have a next steps or more resources, would it be best to add the disclaimer there rather than at the start of the chapter?  It distracts from starting the chapter if that is one of the first things people see.

**Comment by katblanchette** [comment]
In a quick search, we only say next steps and more resources in M1 L5 and [M5 L5](url). Did you see it elsewhere?

**Comment by nasacrawford** [comment]
Most of the  Lesson 5's  have a section on Further Resources or something similar where this would be more appropriate to add it.

**Comment by bressler95tops** [comment]
Thank you @nasacrawford, @katblanchette and I will have a look at these and get disclaimer text inserted

**Comment by katblanchette** [comment]
@bressler95tops - Will you add the disclaimer to each of the additional resource sections? Including a link to M2 here: https://github.com/nasa/Transform-to-Open-Science/tree/open-science-101/Module_2/Lesson_5#additional-tools-for-open-results

**Comment by bressler95tops** [comment]
Thank you [@katblanchette](https://github.com/katblanchette) I have added the disclaimer text in the specified locations.  I was mindful of the placement of the text depending on the important of the information in the section. For your reference (and for the MOOC developers) you may look at PR #798  to see the exact change. 

The exact text change is [under the files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/798/files) of the referenced Pull Request. Let me know when you are able to get that updated on the MOOC or if you have any modifications you would like to make.

**Comment by bressler95tops** [comment]
Thank you for your patience @katblanchette I see this change is done on the MOOC, and likewise here on GitHub.  So I can go ahead and close this issue out and remove the curriculum status label.
