### ISSUE TITLE
Will you release SolarSystem.nasa.gov code?

### ISSUE THREAD

**Issue by grimdeathr** [nasa/Transform-to-Open-Science#80]
https://solarsystem.nasa.gov/planets/saturn/overview/

Would be great for this to be open source so everyone else can also base their solar system simulations on something concrete

**Comment by cgentemann** [comment]
Yes - and there is funding to open-source legacy code:

[F.8 Supplemental Open Source Software Awards](https://nspires.nasaprs.com/external/solicitations/summary!init.do?solId={0BFB6C2C-5189-507A-FB82-E5A9869DF9E4}&path=open)

Supplemental open source software awards are used to encourage the conversion of legacy software into modern code to be released under a generally accepted, open source license (e.g., Apache-2, BSD-2-clause, GPL).
