### ISSUE TITLE
OS101 Module 4 Assessment Question #2

### ISSUE THREAD

**Issue by brian-knosp** [nasa/Transform-to-Open-Science#818]
This question was unclear to a number of test takers.  There seemed to be confusion among the learners about the third item to check off -- almost like a gotcha that it's talking about a repository vs an archive.

**Comment by bressler95tops** [comment]
@katblanchette this is a MOOC only, let me know when it has been addressed

**Comment by katblanchette** [comment]
@brian-knosp  - Thank you for identifying this confusion. @bressler95tops - the OS101 team disposition this comment and the resolution is to remove choice "C" from the options in the assessment. Thank you!

**Comment by bressler95tops** [comment]
@brian-knosp @katblanchette thank you for patience this item has been completed on the MOOC (it only applies to the MOOC in this case) and this issue can now be closed.
