### ISSUE TITLE
Module 1 Global Cooling Error Slide

### ISSUE THREAD

**Issue by brian-knosp** [nasa/Transform-to-Open-Science#824]
One of the learners in my last OS101 training brought up an issue with the Module 1 Global Cooling Error Slide (Slide 16?).  He was in the atmospheric chemistry field at the time when this study came out (and still is in that field).  I have his full comments below, but basically, he was unsure that open science would've fixed the problem that we discuss because he remembers (admittedly vaguely) that it was more an issue with what they were looking at, rather than an error in their research.  I have his full comments below that I wanted to pass along.

> The climate change publication recalling distant memories.
>  
> My recollection is that the 1990s authors plotted a time series of level 1 data from a remote sensing satellite that had a channel that “observes” the temperature of the upper troposphere. I use the term “observes” to mean that the atmosphere appears opaque in the upper troposphere and therefore the signal is its temperature. It produced the unexpected result of no significant trend which was unexpected because the expectation is that we should have seen some warming due to CO2 increase. I suspect that this result was very easily reproduced by subsequent investigators and thus would no longer be publishable because it added nothing new to the existing knowledge base. Thus I would say even though it may have been published in a “closed science” environment, it would have sufficiently satisfied open science objectives. After more investigation and thought, the result was only meaningfull if the vertical sampling of the atmosphere did not change in time. When it was recognized that due to increases in CO2 during the time period, the atmospheric weighting function would rise a bit in altitude thus sampling more colder air because the atmosphere cools as altitude increases causes a cooling tendency when combined with a warming tendency due to CO2 increases cancelled each other out producing a non-statistically significant trend. Thus, the issue here is understanding the nuances behind the data and not that there were errors in the data or the way it was processed. I hope this is helpful.

**Comment by bressler95tops** [comment]
@katblanchette change troposhphere

Errors Discovered

Other scientists found that, due to nuances in the data, the original authors...

**Comment by bressler95tops** [comment]
Change text from 'This oversight introduced errors into the dataset and falsely produced artificial cooling to the temperature measurements.'  to 'This oversight introduced errors in the interpretation of the dataset and falsely produced artificial cooling in the temperature measurements."

**Comment by katblanchette** [comment]
@brian-knosp - Thank you for the information! We have shared this information at our OS101 disposition meeting with our internal team and decided to update the text to reflect the nuances.

**Comment by bressler95tops** [comment]
Also change from 'Eight years after the article was published, other scientists noticed that the original authors didn't account for several important effects.' to  'Eight years after the article was published, other scientists noticed that the original authors didn't account for several important effects, likely due to nuances in the data itself.'

**Comment by bressler95tops** [comment]
@katblanchette I believe the only thing missing for this one is the replacement image like we talked about in the comments above

**Comment by bressler95tops** [comment]
@katblanchette I am marking this as complete on GitHub because of the updated image, check out PRs #842 and #897 for the changes.

**Comment by bressler95tops** [comment]
@brian-knosp @katblanchette thank you for your patience on this, this issue has been addressed both in the MOOC and in the GitHub version of the curriculum.  We appreciate your contributions to our curriculum as always!
