### ISSUE TITLE
Broken link on Module 2 Lesson 3

### ISSUE THREAD

**Issue by SLLDeC** [nasa/Transform-to-Open-Science#830]
Hi, 

There is a broken link on Module 2 Lesson 3 line 97: https://api.openaire.eu/.
Thank you!

**Comment by bressler95tops** [comment]
Thank you @SLLDeC we will add your suggestions to our queue for dispositioning and will let you know if we have any questions for you!

**Comment by bressler95tops** [comment]
@katblanchette replacing with https://explore.openaire.eu/

**Comment by bressler95tops** [comment]
@katblanchette got this one addressed in PR #876.  Likewise, the precise change can be seen in the [files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/876) of that PR.  Let me know when the MOOC developers have had an opportunity to implement this on their end.

**Comment by bressler95tops** [comment]
@SLLDeC @katblanchette Thank you for your patience this change appears to complete on both the MOOC and on GitHub and this issue can now be closed.  We always appreciate your feedback!
