### ISSUE TITLE
Missing link in Module 4 Lesson 1

### ISSUE THREAD

**Issue by SLLDeC** [nasa/Transform-to-Open-Science#831]
Hi,

In the first row of the Fear & Discussion/Mitigation table the text mentions an article, but there is no link:

| Fear | Discussion/Mitigation: |
|---|---|
| Scooping: What if someone re-uses my code to publish a result I was working on? | Yes, this can happen. But, in many fields, if it is clear that someone is actively working on a problem, the decision by another scoop may have a short term gain but long-term loss. In the scientific community, reputations serve as a cultural currency and being collaborative generally leads to increased career successes. If you are sharing your code, ensure it has a digital object identifier (DOI) so you get credit. This does not prevent anyone from using it or extending your analysis, but it does ensure you will get credit for your contribution. There is a nice article about this **here.** |

**Comment by bressler95tops** [comment]
Adding the link to the 'here' text: https://datascience.codata.org/articles/10.5334/dsj-2017-029

**Comment by bressler95tops** [comment]
@katblanchette I got this change pushed through in PR #877. Likewise, the precise change can be seen in the [files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/877/files) in that PR.  Let me know when the MOOC developers have had a chance to implement this.

**Comment by bressler95tops** [comment]
@SLLDeC @katblanchette Thank you for your patience, this change has been completed on the MOOC and on GitHub and this issue can now be closed.  We appreciate your feedback.
