### ISSUE TITLE
Module 2, Lesson 3: broken link

### ISSUE THREAD

**Issue by 4iro** [nasa/Transform-to-Open-Science#832]
The follow link is broken: https://www.rd-alliance.org/group/fair-data-maturity-model-wg/outcomes/fair-data-maturity-model-specification-and-guidelines-0
Thank you!

**Comment by bressler95tops** [comment]
Thank you @4iro we will have a look at your suggestions and at it to our queue for dispositioning!  I will follow up if we have any questions for you.

**Comment by bressler95tops** [comment]
will be replacing with http://dx.doi.org/10.15497/RDA00050

**Comment by katblanchette** [comment]
Thank you @bressler95tops ! And Thank you @4iro for finding the error. :)

**Comment by bressler95tops** [comment]
@katblanchette I got this change pushed through in PR #878.  Likewise, you can see the precise change in the [files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/878/files) of that same PR.  Let me know when the MOOC developers have had a chance to implement this.

**Comment by bressler95tops** [comment]
@4iro @bressler95tops thank you for your patience.  This issue has been resolved on the MOOC and on the GitHub version of the curriculum.  We appreciate your suggestions that will help make OS101 even better!
