### ISSUE TITLE
Module 5 Lesson 3 - TTW link

### ISSUE THREAD

**Issue by 4iro** [nasa/Transform-to-Open-Science#833]
The Turing Way webpage has an announcement that the domain will be changed to https://book.the-turing-way.org/. If you are considering changing the URLs, in Module 5, Lesson 3: https://the-turing-way.netlify.app/collaboration/shared-ownership/shared-ownership-projects.html
Thank you!

**Comment by bressler95tops** [comment]
We will be changing to https://book.the-turing-way.org/

**Comment by bressler95tops** [comment]
@katblanchette I got the link changed for this suggestion in PR #879.  For a detailed viewed on changes, check out the [files changed tab](https://github.com/nasa/Transform-to-Open-Science/pull/879/files) for that same PR.  Let me know when the MOOC developers have had a chance to get this implemented.

**Comment by bressler95tops** [comment]
@4iro @katblanchette thank you for your patience, this issue is resolved on both he MOOC and the GitHub version of OS101, and can likewise be closed.  Thank you for your feedback!
