### ISSUE TITLE
Module 2 - Final Assessment Question on Reference Management Software

### ISSUE THREAD

**Issue by JFormoso** [nasa/Transform-to-Open-Science#843]
In the final assessment, there is a question: Which is NOT a capability of Reference Management Software? The correct answer provided is: Create summaries of research articles. However, one participant from the ALTa Ciencia Abierta training mentioned that with AI integrations (e.g. https://github.com/lifan0127/ai-research-assistant), generating summaries from texts is becoming a possibility. Should the assessment be updated to reflect these emerging capabilities?

**Comment by bressler95tops** [comment]
Thank you @JFormoso we will add your suggestions to our queue for dispositioning, we will let you know if we have any questions.

**Comment by bressler95tops** [comment]
Change title of question to: 

Which is NOT a capability of Reference Management Software? (Excluding AI)
