### ISSUE TITLE
who do I contact?

### ISSUE THREAD

**Issue by WenonahV** [nasa/Transform-to-Open-Science#851]
This is a new platform for me, there are a lot of avenues for possible communication with a person, but it is not clear.  I am taking the TOPS Ethos 101 training, have been looking forward to this for a while!  However, I have questions/feedback about the way the questions are stated, it is kind of not working to be effective for evaluating the level of understanding, which I think is your goal.  Who or how do I provide feedback on this?
Thank you, Wenonah

**Comment by bressler95tops** [comment]
Hey @WenonahV you are in the right place to submit feedback for the Open Science 101 curriculum!  

#### The Easy Way

I would recommend opening an [issue ](https://github.com/nasa/Transform-to-Open-Science/issues) exactly as you have done here and provide a descriptive title and description of what you think could be improved.  The curriculum content exists on GitHub [here](https://github.com/nasa/Transform-to-Open-Science/tree/open-science-101), as it does on openscience101.org.  The difference being that the GitHub version provides a nice way to copy and paste the link where the content can be found more precisely.  

Of course you can always just tell us something along the lines of 'I found this problem in the Assesment for Module 2' or 'I found this problem in Module 2, Lesson 3 under this title' to keep things simple for you.

#### The More Technical Way

There is also this concept of [pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) where you can edit the content directly in a cloned version of the content. This approach is a quite bit more technical than just opening an issue however, especially if you have not done it that way before.

**Comment by bressler95tops** [comment]
Closing out this issue.  Feel free to reopen / request a reopen if you needed more information @WenonahV.

**Comment by WenonahV** [comment]
Hi,Thank you for the response, good to hear these options!As a general observation, as this platform aims to be inclusive, it was surprising to me that there was not an option to have an auditory version.  Perhaps I missed it?  Given that we are NASA people, I’m thinking you’ve taken training classes on SATERN - they always have an accommodating option for hearing the lesson in addition to reading it.  It would be excellent and seems appropriate that this Open Science training would do the same.Thank you,Wenonah On Oct 8, 2024, at 7:20 AM, Brian Ressler ***@***.***> wrote:﻿
Closing out this issue.  Feel free to reopen / request a reopen if you needed more information @WenonahV.

**Comment by bressler95tops** [comment]
> Hi,Thank you for the response, good to hear these options!As a general observation, as this platform aims to be inclusive, it was surprising to me that there was not an option to have an auditory version.  Perhaps I missed it?  Given that we are NASA people, I’m thinking you’ve taken training classes on SATERN - they always have an accommodating option for hearing the lesson in addition to reading it.  It would be excellent and seems appropriate that this Open Science training would do the same.Thank you,Wenonah On Oct 8, 2024, at 7:20 AM, Brian Ressler ***@***.***> wrote:﻿ Closing out this issue. Feel free to reopen / request a reopen if you needed more information @WenonahV. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

That is a great point and is very much something that others have requested. I will say that an audio version (or a version that can easily be played like an audio book with the same content) is something that is being thought about by the project office. I cannot speak to exact progress or when TOPS might officially announce it as something on the timeline.
