### ISSUE TITLE
Module 1 Lesson 2 Repeated word under "Benefits to You"

### ISSUE THREAD

**Issue by bressler95tops** [nasa/Transform-to-Open-Science#855]
**Under title:** Benefits for you

**From:** The TOPS Email Box

"Publicly" is used twice: "Publicly sharing materials publicly makes receiving a citation more likely."

**Comment by bressler95tops** [comment]
Agreed with all changes, delete duplicated changes

**Comment by bressler95tops** [comment]
@katblanchette I went ahead and merged the new image in.  I know you said these were already done on the MOOC but just for reference, PR #912 is where the change occurred.

**Comment by katblanchette** [comment]
@bressler95tops - Thank you for updating the graphic! The change looks good and the OS101 Team thanks you for your efforts. Please close this issue when you are ready.

**Comment by bressler95tops** [comment]
Closing out this issue, it is indeed completed on the MOOC!
