### ISSUE TITLE
Module1 Lesson 2 Several casing corrections

### ISSUE THREAD

**Issue by bressler95tops** [nasa/Transform-to-Open-Science#857]
**Under title:** Benefits to Society

**From:** The TOPS Email Box

Capitalize "Moon"
All caps for "COVID-19" / lowercase "pandemic" / lowercase "open" and "science"

**Comment by bressler95tops** [comment]
Agreed with all changes

**Comment by bressler95tops** [comment]
@katblanchette I went ahead and merged this change in.  I know you said these were already done on the MOOC but just for reference, PR #913 is where the change occurred.

**Comment by katblanchette** [comment]
@bressler95tops - Thank you for updating the graphic! The change looks good and the OS101 Team thanks you for your efforts. Please close this issue when you are ready.

**Comment by bressler95tops** [comment]
This change is complete on both the MOOC and GitHub and the corresponding issue can now be closed here on GitHub. I will likewise removed the MOOC specific status label for tracking purposes.
