### ISSUE TITLE
Translation suggestions

### ISSUE THREAD

**Issue by lauracion** [nasa/Transform-to-Open-Science#872]
I was unable to find all the files that make [this page](https://nasa.github.io/Transform-to-Open-Science/os101-en-espanol/). Thus, including here some additional suggestions for changing the Spanish version of the website that were not submitted over PRs.

- "Si desea obtener más información sobre la versión en inglés de nuestro curso, [visite aquí](https://nasa.github.io/Transform-to-Open-Science/take-os101/), o si desea suscribirse a nuestro boletín en inglés, [visite aquí](https://nasa.github.io/Transform-to-Open-Science/signup/)." should be "Si deseas obtener más información sobre la versión en inglés de nuestro curso, [visita aquí](https://nasa.github.io/Transform-to-Open-Science/take-os101/), o si deseas suscribirte a nuestro boletín en inglés, [visita aquí](https://nasa.github.io/Transform-to-Open-Science/signup/).
- "Al enviar este formulario, usted acepta recibir actualizaciones de esta dirección: NASA Transform to Open Science (TOPS), 320 Sparkman Dr , Huntsville, AL, 35805, US, https://nasa.github.io/Transform-to-Open-Science/. Puede revocar su consentimiento para recibir correos electrónicos en cualquier momento utilizando el enlace SafeUnsubscribe®, que se encuentra en la parte inferior de cada correo electrónico." should be "Al enviar este formulario, aceptas recibir actualizaciones de esta dirección: NASA Transform to Open Science (TOPS), 320 Sparkman Dr , Huntsville, AL, 35805, US, https://nasa.github.io/Transform-to-Open-Science/. Puedes revocar tu consentimiento para recibir correos electrónicos en cualquier momento utilizando el enlace SafeUnsubscribe®, que se encuentra en la parte inferior de cada correo electrónico."
- "Suscribir!" should be "¡Suscríbete!"

**Comment by bressler95tops** [comment]
Thank you @lauracion these changes are great.  I will get those into the promotion page.

**Comment by bressler95tops** [comment]
Thank you for patience @lauracion I have merged your PRs and have implemented the suggestions you made here.
