### ISSUE TITLE
Add OLS October virtual cohort

### ISSUE THREAD

**Issue by iramosp** [nasa/Transform-to-Open-Science#873]
Hi @bressler95tops, 

This is Irene, from the @open-life-science team, one of NASA TOPS grantees. 
Could you help us add our upcoming cohort to the OS101 event tracker, please?

Here is the event information:

- **Date:** October 22 - November 28
- **Time:** 4:00 - 5:30 PM (UTC)
- **Event type:** OLS-NASA Nebula Program
- **Topic:** OS101 Modules 1 to 5
- **Instructors:** OLS Team: Virginia García Alonso, Chad Sansing, Jafsia Elisée, Saranjeet Kaur Bhogal, Sara Villa, Pauline Karega, Johanna Bayer, Aman Goel, Daniela Saderi
- **Registration type:** External (OLS)
- **Registration link:** https://events.humanitix.com/ols-nebula

Please let me know if there is a better channel for this request.
Thank you!

**Comment by bressler95tops** [comment]
Hi @iramosp, thanks for reaching out.  I can see that OLS is on our biweekly morning calls that we do with TOPST and TOPS champions.  Did you or anyone on your team get a link to our Google Table?  This is the method that we suggest for everyone to add their workshops internally.  Otherwise, for this time, I can get this to the team and get your workshop added.

**Comment by iramosp** [comment]
Thanks for looking into this. We got a link that unfortunately is not accessible from outside the US. I also tried emailing the info, but both tries bounced back. 

> Otherwise, I can get this to the team and get your workshop added

I'd appreciate this, thank you!

**Comment by bressler95tops** [comment]
@iramosp got this in front of everyone today just to verify a few things.  But your cohort is now up [at this link!](https://nasa.github.io/Transform-to-Open-Science/take-os101/#instructorled) It's under the Virtual Tab.

**Comment by iramosp** [comment]
Thank you!!
