### ISSUE TITLE
Re-add the word "for" into the sentence.

### ISSUE THREAD

**Issue by katblanchette** [nasa/Transform-to-Open-Science#882]
@bressler1995  - will you re-add the word "for" into the sentence "At a minimum, a software management plan SMD-funded (NASA Science Mission Directorate) research should include:". Here is the new sentence, "At a minimum, a software management plan for SMD-funded (NASA Science Mission Directorate) research should include:" Here is the link to the original update: https://teams.microsoft.com/l/message/19:meeting_MWJmNzU1MTQtMmFiMy00MjY0LTgwY2YtNzFjY2IxOTVlYzZh@thread.v2/1728325735875?context=%7B%22contextType%22%3A%22chat%22%7D Thank you!!

**Comment by bressler95tops** [comment]
@katblanchette I did this on GitHub a little while ago, that exact change is in #915.  Interestingly I also noticed this was done on the MOOC, you may have submitted this with having already been done there.  So I should be able to officially check this one off.
