### ISSUE TITLE
Export Administration Regulations link is broken

### ISSUE THREAD

**Issue by SofiaFanourakis** [nasa/Transform-to-Open-Science#887]
In Module 4 Lesson 3, the updated link to EAR is also broken and leads to a 404 page. In "[Export Administration Regulations](https://www.bis.gov/regulations/ear-overview) (EAR), which regulates the manufacture, sale, distribution, and export of commercial and dual- use items, technology, and information not already covered by ITAR" the new link should be: https://www.bis.gov/regulations

**Comment by bressler95tops** [comment]
Thanks @SofiaFanourakis, I see Katherine also tagged me in Issue #729, so I will make sure to reference that
