### ISSUE TITLE
Replace M3 L3 License Graphic with Two New Graphics

### ISSUE THREAD

**Issue by katblanchette** [nasa/Transform-to-Open-Science#903]
[Link](https://drive.google.com/file/d/1pfHHEr6F9TgdGiXX3g5egzH5ZfBpXSFC/view)

**Comment by katblanchette** [comment]
[2nd link](https://drive.google.com/file/d/1_0AF4VFJ_0mnfc-ioegPt6X1_aLReuq3/view)

**Comment by katblanchette** [comment]
@bressler1995 - Will you replace the original graphic with these two new updated versions of the graphic. They should be side by side in the lesson. The original graphic is Module_3/images/media/image34.jpeg.

**Comment by bressler95tops** [comment]
@katblanchette I replaced the image with the two images side by side as was possible in the GitHub environment.  The exact change is in PR #919 and as usual the precise change is in the 'files changed' tab when you are in that PR.

**Comment by katblanchette** [comment]
Thank you @bressler95tops for updating the graphics. The OS101 Team as reviewed the update and are satisfied with the change. Please close this issue when you are ready and thank you for your efforts!

**Comment by bressler95tops** [comment]
I can this change has been completed on the MOOC and this issue can now be closed.
