### ISSUE TITLE
Replace M4 L3 Image

### ISSUE THREAD

**Issue by katblanchette** [nasa/Transform-to-Open-Science#904]
https://github.com/nasa/Transform-to-Open-Science/tree/open-science-101/Module_4/Lesson_3#some-common-types-of-software-license @bressler1995  - Will you update the Openness is a Spectrum graphic within this section? Here is the link to the new graphic - [link](https://drive.google.com/drive/folders/1NWtKqR6GuqmpF9HgoYGOTFLjyT_VkF3p). Thank you!

**Comment by bressler95tops** [comment]
@katblanchette got this image replaced on my end, I noticed that it was vertical and the text was difficult to read in that position so I rotated it horizontally.  For your reference PR #918 is where the change occurred and you can see precise details in the 'files changed' tab when viewing that PR.

**Comment by katblanchette** [comment]
@bressler95tops - Thank you for updating the graphic! The change looks good and the OS101 Team thanks you for your efforts. Please close this issue when you are ready.

**Comment by bressler95tops** [comment]
I see that this change was completed on the MOOC and this issue can now be closed.
