### ISSUE TITLE
Replace M2 L1 Graphic

### ISSUE THREAD

**Issue by katblanchette** [nasa/Transform-to-Open-Science#906]
https://github.com/nasa/Transform-to-Open-Science/tree/open-science-101/Module_2/Lesson_1#the-components-of-open-science - @bressler1995 - Please replace the pyramid graphic with this new graphic. [Link](https://drive.google.com/file/d/1oz663gN63wFvA_wZfPJHKliAYOpCV_Ax/view) - Thank you! Katherine

**Comment by bressler95tops** [comment]
@katblanchette I went ahead and merged the new image in.  I know you said these were already done on the MOOC but just for reference, PR #916 is where the change occurred.

**Comment by katblanchette** [comment]
@bressler95tops - Thank you for updating the graphic! The change looks good and the OS101 Team thanks you for your efforts. Please close this issue when you are ready.

**Comment by bressler95tops** [comment]
I see that this issue was also completed on the MOOC and this issue can likewise be closed.
