### ISSUE TITLE
Update Graphic - M1 L5

### ISSUE THREAD

**Issue by katblanchette** [nasa/Transform-to-Open-Science#925]
@bressler1995  - Will you replace the cloud graphic with the new Prof. Paul graphic linked here]{(https://drive.google.com/file/d/1srYMF37FEjmVGTFWA2KG4oFfRPghG95h/view).  Module 1 Lesson 5. Thank you!

**Comment by bressler95tops** [comment]
@katblanchette I have replaced the graphic on GitHub and I can see it has also been replaced on the MOOC, and I can likewise mark this issue as completed.
